MAX_LEVEL = 100
MIN_LEVEL = 2
EGG_LEVEL = 5

NUM_MOVES = 4

BASE_STAT_LEVEL = 7
MAX_STAT_LEVEL = 13

REST_SLEEP_TURNS = 2
TREEMON_SLEEP_TURNS = 7

BASE_PRIORITY = 1

SUPER_EFFECTIVE = 20
MORE_EFFECTIVE = 15
EFFECTIVE = 10
NOT_VERY_EFFECTIVE = 5
NO_EFFECT = 0

BASE_AI_SWITCH_SCORE = 10

.enum 0
ATTACK:		.dsb 1
DEFENSE:	.dsb 1
SPEED:		.dsb 1
SP_ATTACK:	.dsb 1
SP_DEFENSE:	.dsb 1
ACCURACY:	.dsb 1
EVASION:	.dsb 1
ABILITY:	.dsb 1
NUM_LEVEL_STATS:
.ende

.enum 0
MOVE_ANIM:	.dsb 1
MOVE_EFFECT:	.dsb 1
MOVE_POWER:	.dsb 1
MOVE_TYPE:	.dsb 1
MOVE_ACC:	.dsb 1
MOVE_PP:	.dsb 1
MOVE_CHANCE:	.dsb 1
MOVE_LENGTH:
.ende

.enum 1
STAT_HP:	.dsb 1
STAT_ATK:	.dsb 1
STAT_DEF:	.dsb 1
STAT_SPD:	.dsb 1
STAT_SATK:
NUM_EXP_STATS:
	.dsb 1
STAT_SDEF:
NUM_STATS:
	.dsb 1
.ende
NUM_BATTLE_STATS = NUM_STATS - 1

STAT_MIN_NORMAL = 5
STAT_MIN_HP = 10

MAX_STAT_VALUE = 999

ATKDEFDV_SHINY = $EA
SPDSPCDV_SHINY = $AA

.enum 1
WILD_BATTLE:	.dsb 1
TRAINER_BATTLE:
.ende

.enum 0
BATTLETYPE_NORMAL:	.dsb 1
BATTLETYPE_CANLOSE:	.dsb 1
BATTLETYPE_DEBUG:	.dsb 1
BATTLETYPE_TUTORIAL:	.dsb 1
BATTLETYPE_FISH:	.dsb 1
BATTLETYPE_ROAMING:	.dsb 1
BATTLETYPE_CONTEST:	.dsb 1
BATTLETYPE_FORCESHINY:	.dsb 1
BATTLETYPE_TREE:	.dsb 1
BATTLETYPE_TRAP:	.dsb 1
BATTLETYPE_FORCEITEM:
.ende

.enum 0
BATTLE_VARS_SUBSTATUS1:			.dsb 1
BATTLE_VARS_SUBSTATUS2:			.dsb 1
BATTLE_VARS_SUBSTATUS3:			.dsb 1
BATTLE_VARS_SUBSTATUS4:			.dsb 1
BATTLE_VARS_SUBSTATUS5:			.dsb 1
BATTLE_VARS_SUBSTATUS1_OPP:		.dsb 1
BATTLE_VARS_SUBSTATUS2_OPP:		.dsb 1
BATTLE_VARS_SUBSTATUS3_OPP:		.dsb 1
BATTLE_VARS_SUBSTATUS4_OPP:		.dsb 1
BATTLE_VARS_SUBSTATUS5_OPP:		.dsb 1
BATTLE_VARS_STATUS:			.dsb 1
BATTLE_VARS_STATUS_OPP:			.dsb 1
BATTLE_VARS_MOVE_ANIM:			.dsb 1
BATTLE_VARS_MOVE_EFFECT:		.dsb 1
BATTLE_VARS_MOVE_POWER:			.dsb 1
BATTLE_VARS_MOVE_TYPE:			.dsb 1
BATTLE_VARS_MOVE:			.dsb 1
BATTLE_VARS_LAST_COUNTER_MOVE:		.dsb 1
BATTLE_VARS_LAST_COUNTER_MOVE_OPP:	.dsb 1
BATTLE_VARS_LAST_MOVE:			.dsb 1
BATTLE_VARS_LAST_MOVE_OPP:		.dsb 1
NUM_BATTLE_VARS:
.ende

.enum 0
PLAYER_SUBSTATUS_1:	.dsb 1
ENEMY_SUBSTATUS_1:	.dsb 1
PLAYER_SUBSTATUS_2:	.dsb 1
ENEMY_SUBSTATUS_2:	.dsb 1
PLAYER_SUBSTATUS_3:	.dsb 1
ENEMY_SUBSTATUS_3:	.dsb 1
PLAYER_SUBSTATUS_4:	.dsb 1
ENEMY_SUBSTATUS_4:	.dsb 1
PLAYER_SUBSTATUS_5:	.dsb 1
ENEMY_SUBSTATUS_5:	.dsb 1
PLAYER_STATUS:		.dsb 1
ENEMY_STATUS:		.dsb 1
PLAYER_MOVE_ANIMATION:	.dsb 1
ENEMY_MOVE_ANIMATION:	.dsb 1
PLAYER_MOVE_EFFECT:	.dsb 1
ENEMY_MOVE_EFFECT:	.dsb 1
PLAYER_MOVE_POWER:	.dsb 1
ENEMY_MOVE_POWER:	.dsb 1
PLAYER_MOVE_TYPE:	.dsb 1
ENEMY_MOVE_TYPE:	.dsb 1
PLAYER_CUR_MOVE:	.dsb 1
ENEMY_CUR_MOVE:		.dsb 1
PLAYER_COUNTER_MOVE:	.dsb 1
ENEMY_COUNTER_MOVE:	.dsb 1
PLAYER_LAST_MOVE:	.dsb 1
ENEMY_LAST_MOVE:	.dsb 1
NUM_BATTLE_VAR_LOCATIONS:
.ende

NUM_BATTLE_VAR_LOCATION_PAIRS = NUM_BATTLE_VAR_LOCATIONS / 2

SLP_MASK = %111
.enum 3
PSN:	.dsb 1
BRN:	.dsb 1
FRZ:	.dsb 1
PAR:
.ende

ALL_STATUS = (1 << PSN) | (1 << BRN) | (1 << FRZ) | (1 << PAR) | SLP_MASK

.enum 0
SUBSTATUS_NIGHTMARE:	.dsb 1
SUBSTATUS_CURSE:	.dsb 1
SUBSTATUS_PROTECT:	.dsb 1
SUBSTATUS_IDENTIFIED:	.dsb 1
SUBSTATUS_PERISH:	.dsb 1
SUBSTATUS_ENDURE:	.dsb 1
SUBSTATUS_ROLLOUT:	.dsb 1
SUBSTATUS_IN_LOVE:
.ende

SUBSTATUS_CURLED = 0

.enum 0
SUBSTATUS_BIDE:		.dsb 1
SUBSTATUS_RAMPAGE:	.dsb 1
SUBSTATUS_IN_LOOP:	.dsb 1
SUBSTATUS_FLINCHED:	.dsb 1
SUBSTATUS_CHARGED:	.dsb 1
SUBSTATUS_UNDERGROUND:	.dsb 1
SUBSTATUS_FLYING:	.dsb 1
SUBSTATUS_CONFUSED:
.ende

.enum 0
SUBSTATUS_X_ACCURACY:	.dsb 1
SUBSTATUS_MIST:		.dsb 1
SUBSTATUS_FOCUS_ENERGY:	.dsb 1
	.dsb 1
SUBSTATUS_SUBSTITUTE:	.dsb 1
SUBSTATUS_RECHARGE:	.dsb 1
SUBSTATUS_RAGE:		.dsb 1
SUBSTATUS_LEECH_SEED:
.ende

.enum 0
SUBSTATUS_TOXIC:	.dsb 1
	.dsb 1
	.dsb 1
SUBSTATUS_TRANSFORMED:	.dsb 1
SUBSTATUS_ENCORED:	.dsb 1
SUBSTATUS_LOCK_ON:	.dsb 1
SUBSTATUS_DESTINY_BOND:	.dsb 1
SUBSTATUS_CANT_RUN:	.dsb 1
.ende

.enum 0
SCREENS_SPIKES:		.dsb 1
	.dsb 1
SCREENS_SAFEGUARD:	.dsb 1
SCREENS_LIGHT_SCREEN:	.dsb 1
SCREENS_REFLECT:	.dsb 1
.ende

.enum 0
WEATHER_NONE:		.dsb 1
WEATHER_RAIN:		.dsb 1
WEATHER_SUN:		.dsb 1
WEATHER_SANDSTORM:	.dsb 1
WEATHER_RAIN_END:	.dsb 1
WEATHER_SUN_END:	.dsb 1
WEATHER_SANDSTORM_END:
.ende

.enum 0
BATTLEACTION_MOVE1:	.dsb 1
BATTLEACTION_MOVE2:	.dsb 1
BATTLEACTION_MOVE3:	.dsb 1
BATTLEACTION_MOVE4:	.dsb 1
BATTLEACTION_SWITCH1:	.dsb 1
BATTLEACTION_SWITCH2:	.dsb 1
BATTLEACTION_SWITCH3:	.dsb 1
BATTLEACTION_SWITCH4:	.dsb 1
BATTLEACTION_SWITCH5:	.dsb 1
BATTLEACTION_SWITCH6:	.dsb 1
	.dsb 1
	.dsb 1
	.dsb 1
BATTLEACTION_SKIPTURN:	.dsb 1
BATTLEACTION_STRUGGLE:	.dsb 1
BATTLEACTION_FORFEIT:	.dsb 1
.ende

.enum 0
BATTLEPLAYERACTION_USEMOVE:	.dsb 1
BATTLEPLAYERACTION_USEITEM:	.dsb 1
BATTLEPLAYERACTION_SWITCH:	.dsb 1
.ende

.enum 0
WIN:	.dsb 1
LOSE:	.dsb 1
DRAW:	.dsb 1
.ende

BATTLERESULT_BOX_FULL = 7
BATTLERESULT_BITMASK = (1 << BATTLERESULT_BOX_FULL)

.enum 0
BAT_SPECIES:	.dsb 1
BAT_ITEM:	.dsb 1
BAT_MOVES:	.dsb NUM_MOVES
BAT_DVS:	.dsb 2
BAT_PP:		.dsb NUM_MOVES
BAT_HAPPINESS:	.dsb 1
BAT_LEVEL:	.dsb 1
BAT_STATUS:	.dsb 1
	.dsb 1
BAT_HP:		.dsb 2
BAT_MAXHP:	.dsb 2
BAT_STATS:
BAT_ATK:	.dsb 2
BAT_DEF:	.dsb 2
BAT_SPD:	.dsb 2
BAT_SAT:	.dsb 2
BAT_SDF:	.dsb 2
BAT_TYPE:
BAT_TYPE_1:	.dsb 1
BAT_TYPE_2:	.dsb 1
BAT_STRUCT_LENGTH:
.ende
