; EngineFlags indexes (see data/events/engine-flags.asm)
.enum 0
; wPokegearFlags
ENGINE_RADIO_CARD:				.dsb 1
ENGINE_MAP_CARD:				.dsb 1
ENGINE_PHONE_CARD:				.dsb 1
ENGINE_EXPN_CARD:				.dsb 1
ENGINE_POKEGEAR:				.dsb 1
; wDayCareMan
ENGINE_DAY_CARE_MAN_HAS_EGG:			.dsb 1
ENGINE_DAY_CARE_MAN_HAS_MON:			.dsb 1
; wDayCareLady
ENGINE_DAY_CARE_LADY_HAS_MON:			.dsb 1
; wMomSavingMoney
ENGINE_MOM_SAVING_MONEY:			.dsb 1
ENGINE_MOM_ACTIVE:				.dsb 1
; wUnusedTwoDayTimerOn
ENGINE_UNUSED_TWO_DAY_TIMER_ON:			.dsb 1
; wStatusFlags
ENGINE_POKEDEX:					.dsb 1
ENGINE_UNOWN_DEX:				.dsb 1
ENGINE_CAUGHT_POKERUS:				.dsb 1
ENGINE_ROCKET_SIGNAL_ON_CH20:			.dsb 1
ENGINE_CREDITS_SKIP:				.dsb 1
; wStatusFlags2
ENGINE_BUG_CONTEST_TIMER:			.dsb 1
ENGINE_SAFARI_ZONE:				.dsb 1
ENGINE_ROCKETS_IN_RADIO_TOWER:			.dsb 1
ENGINE_BIKE_SHOP_CALL_ENABLED:			.dsb 1
ENGINE_14:					.dsb 1
ENGINE_REACHED_GOLDENROD:			.dsb 1
ENGINE_ROCKETS_IN_MAHOGANY:			.dsb 1
; wBikeFlags
ENGINE_STRENGTH_ACTIVE:				.dsb 1
ENGINE_ALWAYS_ON_BIKE:				.dsb 1
ENGINE_DOWNHILL:				.dsb 1
; wJohtoBadges
ENGINE_ZEPHYRBADGE:				.dsb 1
ENGINE_HIVEBADGE:				.dsb 1
ENGINE_PLAINBADGE:				.dsb 1
ENGINE_FOGBADGE:				.dsb 1
ENGINE_MINERALBADGE:				.dsb 1
ENGINE_STORMBADGE:				.dsb 1
ENGINE_GLACIERBADGE:				.dsb 1
ENGINE_RISINGBADGE:				.dsb 1
; wKantoBadges
ENGINE_BOULDERBADGE:				.dsb 1
ENGINE_CASCADEBADGE:				.dsb 1
ENGINE_THUNDERBADGE:				.dsb 1
ENGINE_RAINBOWBADGE:				.dsb 1
ENGINE_SOULBADGE:				.dsb 1
ENGINE_MARSHBADGE:				.dsb 1
ENGINE_VOLCANOBADGE:				.dsb 1
ENGINE_EARTHBADGE:				.dsb 1
; wUnlockedUnowns
ENGINE_UNLOCKED_UNOWNS_A_TO_K:			.dsb 1
ENGINE_UNLOCKED_UNOWNS_L_TO_R:			.dsb 1
ENGINE_UNLOCKED_UNOWNS_S_TO_W:			.dsb 1
ENGINE_UNLOCKED_UNOWNS_X_TO_Z:			.dsb 1
ENGINE_UNLOCKED_UNOWNS_UNUSED_4:		.dsb 1
ENGINE_UNLOCKED_UNOWNS_UNUSED_5:		.dsb 1
ENGINE_UNLOCKED_UNOWNS_UNUSED_6:		.dsb 1
ENGINE_UNLOCKED_UNOWNS_UNUSED_7:		.dsb 1
; wVisitedSpawns
ENGINE_FLYPOINT_PLAYERS_HOUSE:			.dsb 1
ENGINE_FLYPOINT_DEBUG:				.dsb 1
ENGINE_FLYPOINT_PALLET:				.dsb 1
ENGINE_FLYPOINT_VIRIDIAN:			.dsb 1
ENGINE_FLYPOINT_PEWTER:				.dsb 1
ENGINE_FLYPOINT_CERULEAN:			.dsb 1
ENGINE_FLYPOINT_ROCK_TUNNEL:			.dsb 1
ENGINE_FLYPOINT_VERMILION:			.dsb 1
ENGINE_FLYPOINT_LAVENDER:			.dsb 1
ENGINE_FLYPOINT_SAFFRON:			.dsb 1
ENGINE_FLYPOINT_CELADON:			.dsb 1
ENGINE_FLYPOINT_FUCHSIA:			.dsb 1
ENGINE_FLYPOINT_CINNABAR:			.dsb 1
ENGINE_FLYPOINT_INDIGO_PLATEAU:			.dsb 1
ENGINE_FLYPOINT_NEW_BARK:			.dsb 1
ENGINE_FLYPOINT_CHERRYGROVE:			.dsb 1
ENGINE_FLYPOINT_VIOLET:				.dsb 1
ENGINE_FLYPOINT_AZALEA:				.dsb 1
ENGINE_FLYPOINT_CIANWOOD:			.dsb 1
ENGINE_FLYPOINT_GOLDENROD:			.dsb 1
ENGINE_FLYPOINT_OLIVINE:			.dsb 1
ENGINE_FLYPOINT_ECRUTEAK:			.dsb 1
ENGINE_FLYPOINT_MAHOGANY:			.dsb 1
ENGINE_FLYPOINT_LAKE_OF_RAGE:			.dsb 1
ENGINE_FLYPOINT_BLACKTHORN:			.dsb 1
ENGINE_FLYPOINT_SILVER_CAVE:			.dsb 1
ENGINE_FLYPOINT_UNUSED:				.dsb 1
; wLuckyNumberShowFlag
ENGINE_LUCKY_NUMBER_SHOW:			.dsb 1
; wStatusFlags2
ENGINE_4E:					.dsb 1
; wDailyFlags1
ENGINE_KURT_MAKING_BALLS:			.dsb 1
ENGINE_DAILY_BUG_CONTEST:			.dsb 1
ENGINE_SWARM:					.dsb 1
ENGINE_TIME_CAPSULE:				.dsb 1
ENGINE_ALL_FRUIT_TREES:				.dsb 1
ENGINE_GOT_SHUCKIE_TODAY:			.dsb 1
ENGINE_GOLDENROD_UNDERGROUND_MERCHANT_CLOSED:	.dsb 1
ENGINE_FOUGHT_IN_TRAINER_HALL_TODAY:		.dsb 1
; wDailyFlags2
ENGINE_MT_MOON_SQUARE_CLEFAIRY:			.dsb 1
ENGINE_UNION_CAVE_LAPRAS:			.dsb 1
ENGINE_GOLDENROD_UNDERGROUND_GOT_HAIRCUT:	.dsb 1
ENGINE_GOLDENROD_DEPT_STORE_TM27_RETURN:	.dsb 1
ENGINE_DAISYS_GROOMING:				.dsb 1
ENGINE_INDIGO_PLATEAU_RIVAL_FIGHT:		.dsb 1
NUM_ENGINE_FLAGS:
.ende
