A_BUTTON = $80
B_BUTTON = $40
START_BUTTON = $20
SELECT_BUTTON = $10
D_UP = $08
D_DOWN = $04
D_LEFT = $02
D_RIGHT = $01

NO_INPUT = 0

BUTTONS = A_BUTTON | B_BUTTON | START_BUTTON | SELECT_BUTTON
D_PAD = D_UP | D_DOWN | D_LEFT | D_RIGHT
