; item ids
; indexes for:
; - ItemNames (see data/items/names.asm)
; - ItemDescriptions (see data/items/descriptions.asm)
; - ItemAttributes (see data/items/attributes.asm)
; - ItemEffects (see engine/items/item_effects.asm)
.enum 0
NO_ITEM:	.dsb 1 ; 00
MASTER_BALL:	.dsb 1 ; 01
ULTRA_BALL:	.dsb 1 ; 02
BRIGHTPOWDER:	.dsb 1 ; 03
GREAT_BALL:	.dsb 1 ; 04
POKE_BALL:	.dsb 1 ; 05
TOWN_MAP:	.dsb 1 ; 06
BICYCLE:	.dsb 1 ; 07
MOON_STONE:	.dsb 1 ; 08
ANTIDOTE:	.dsb 1 ; 09
BURN_HEAL:	.dsb 1 ; 0a
ICE_HEAL:	.dsb 1 ; 0b
AWAKENING:	.dsb 1 ; 0c
PARLYZ_HEAL:	.dsb 1 ; 0d
FULL_RESTORE:	.dsb 1 ; 0e
MAX_POTION:	.dsb 1 ; 0f
HYPER_POTION:	.dsb 1 ; 10
SUPER_POTION:	.dsb 1 ; 11
POTION:		.dsb 1 ; 12
ESCAPE_ROPE:	.dsb 1 ; 13
REPEL:		.dsb 1 ; 14
MAX_ELIXER:	.dsb 1 ; 15
FIRE_STONE:	.dsb 1 ; 16
THUNDERSTONE:	.dsb 1 ; 17
WATER_STONE:	.dsb 1 ; 18
ITEM_19:	.dsb 1 ; 19
HP_UP:		.dsb 1 ; 1a
PROTEIN:	.dsb 1 ; 1b
IRON:		.dsb 1 ; 1c
CARBOS:		.dsb 1 ; 1d
LUCKY_PUNCH:	.dsb 1 ; 1e
CALCIUM:	.dsb 1 ; 1f
RARE_CANDY:	.dsb 1 ; 20
X_ACCURACY:	.dsb 1 ; 21
LEAF_STONE:	.dsb 1 ; 22
METAL_POWDER:	.dsb 1 ; 23
NUGGET:		.dsb 1 ; 24
POKE_DOLL:	.dsb 1 ; 25
FULL_HEAL:	.dsb 1 ; 26
REVIVE:		.dsb 1 ; 27
MAX_REVIVE:	.dsb 1 ; 28
GUARD_SPEC:	.dsb 1 ; 29
SUPER_REPEL:	.dsb 1 ; 2a
MAX_REPEL:	.dsb 1 ; 2b
DIRE_HIT:	.dsb 1 ; 2c
ITEM_2D:	.dsb 1 ; 2d
FRESH_WATER:	.dsb 1 ; 2e
SODA_POP:	.dsb 1 ; 2f
LEMONADE:	.dsb 1 ; 30
X_ATTACK:	.dsb 1 ; 31
ITEM_32:	.dsb 1 ; 32
X_DEFEND:	.dsb 1 ; 33
X_SPEED:	.dsb 1 ; 34
X_SPECIAL:	.dsb 1 ; 35
COIN_CASE:	.dsb 1 ; 36
ITEMFINDER:	.dsb 1 ; 37
POKE_FLUTE:	.dsb 1 ; 38
EXP_SHARE:	.dsb 1 ; 39
OLD_ROD:	.dsb 1 ; 3a
GOOD_ROD:	.dsb 1 ; 3b
SILVER_LEAF:	.dsb 1 ; 3c
SUPER_ROD:	.dsb 1 ; 3d
PP_UP:		.dsb 1 ; 3e
ETHER:		.dsb 1 ; 3f
MAX_ETHER:	.dsb 1 ; 40
ELIXER:		.dsb 1 ; 41
RED_SCALE:	.dsb 1 ; 42
SECRETPOTION:	.dsb 1 ; 43
S_S_TICKET:	.dsb 1 ; 44
MYSTERY_EGG:	.dsb 1 ; 45
ITEM_46:	.dsb 1 ; 46
SILVER_WING:	.dsb 1 ; 47
MOOMOO_MILK:	.dsb 1 ; 48
QUICK_CLAW:	.dsb 1 ; 49
PSNCUREBERRY:	.dsb 1 ; 4a
GOLD_LEAF:	.dsb 1 ; 4b
SOFT_SAND:	.dsb 1 ; 4c
SHARP_BEAK:	.dsb 1 ; 4d
PRZCUREBERRY:	.dsb 1 ; 4e
BURNT_BERRY:	.dsb 1 ; 4f
ICE_BERRY:	.dsb 1 ; 50
POISON_BARB:	.dsb 1 ; 51
KINGS_ROCK:	.dsb 1 ; 52
BITTER_BERRY:	.dsb 1 ; 53
MINT_BERRY:	.dsb 1 ; 54
RED_APRICORN:	.dsb 1 ; 55
TINYMUSHROOM:	.dsb 1 ; 56
BIG_MUSHROOM:	.dsb 1 ; 57
SILVERPOWDER:	.dsb 1 ; 58
BLU_APRICORN:	.dsb 1 ; 59
ITEM_5A:	.dsb 1 ; 5a
AMULET_COIN:	.dsb 1 ; 5b
YLW_APRICORN:	.dsb 1 ; 5c
GRN_APRICORN:	.dsb 1 ; 5d
CLEANSE_TAG:	.dsb 1 ; 5e
MYSTIC_WATER:	.dsb 1 ; 5f
TWISTEDSPOON:	.dsb 1 ; 60
WHT_APRICORN:	.dsb 1 ; 61
BLACKBELT_I:	.dsb 1 ; 62
BLK_APRICORN:	.dsb 1 ; 63
ITEM_64:	.dsb 1 ; 64
PNK_APRICORN:	.dsb 1 ; 65
BLACKGLASSES:	.dsb 1 ; 66
SLOWPOKETAIL:	.dsb 1 ; 67
PINK_BOW:	.dsb 1 ; 68
STICK:		.dsb 1 ; 69
SMOKE_BALL:	.dsb 1 ; 6a
NEVERMELTICE:	.dsb 1 ; 6b
MAGNET:		.dsb 1 ; 6c
MIRACLEBERRY:	.dsb 1 ; 6d
PEARL:		.dsb 1 ; 6e
BIG_PEARL:	.dsb 1 ; 6f
EVERSTONE:	.dsb 1 ; 70
SPELL_TAG:	.dsb 1 ; 71
RAGECANDYBAR:	.dsb 1 ; 72
ITEM_73:	.dsb 1 ; 73
ITEM_74:	.dsb 1 ; 74
MIRACLE_SEED:	.dsb 1 ; 75
THICK_CLUB:	.dsb 1 ; 76
FOCUS_BAND:	.dsb 1 ; 77
ITEM_78:	.dsb 1 ; 78
ENERGYPOWDER:	.dsb 1 ; 79
ENERGY_ROOT:	.dsb 1 ; 7a
HEAL_POWDER:	.dsb 1 ; 7b
REVIVAL_HERB:	.dsb 1 ; 7c
HARD_STONE:	.dsb 1 ; 7d
LUCKY_EGG:	.dsb 1 ; 7e
CARD_KEY:	.dsb 1 ; 7f
MACHINE_PART:	.dsb 1 ; 80
ITEM_81:	.dsb 1 ; 81
LOST_ITEM:	.dsb 1 ; 82
STARDUST:	.dsb 1 ; 83
STAR_PIECE:	.dsb 1 ; 84
BASEMENT_KEY:	.dsb 1 ; 85
PASS:		.dsb 1 ; 86
ITEM_87:	.dsb 1 ; 87
ITEM_88:	.dsb 1 ; 88
ITEM_89:	.dsb 1 ; 89
CHARCOAL:	.dsb 1 ; 8a
BERRY_JUICE:	.dsb 1 ; 8b
SCOPE_LENS:	.dsb 1 ; 8c
ITEM_8D:	.dsb 1 ; 8d
ITEM_8E:	.dsb 1 ; 8e
METAL_COAT:	.dsb 1 ; 8f
DRAGON_FANG:	.dsb 1 ; 90
ITEM_91:	.dsb 1 ; 91
LEFTOVERS:	.dsb 1 ; 92
ITEM_93:	.dsb 1 ; 93
ITEM_94:	.dsb 1 ; 94
ITEM_95:	.dsb 1 ; 95
MYSTERYBERRY:	.dsb 1 ; 96
DRAGON_SCALE:	.dsb 1 ; 97
BERSERK_GENE:	.dsb 1 ; 98
ITEM_99:	.dsb 1 ; 99
ITEM_9A:	.dsb 1 ; 9a
ITEM_9B:	.dsb 1 ; 9b
SACRED_ASH:	.dsb 1 ; 9c
HEAVY_BALL:	.dsb 1 ; 9d
FLOWER_MAIL:	.dsb 1 ; 9e
LEVEL_BALL:	.dsb 1 ; 9f
LURE_BALL:	.dsb 1 ; a0
FAST_BALL:	.dsb 1 ; a1
ITEM_A2:	.dsb 1 ; a2
LIGHT_BALL:	.dsb 1 ; a3
FRIEND_BALL:	.dsb 1 ; a4
MOON_BALL:	.dsb 1 ; a5
LOVE_BALL:	.dsb 1 ; a6
NORMAL_BOX:	.dsb 1 ; a7
GORGEOUS_BOX:	.dsb 1 ; a8
SUN_STONE:	.dsb 1 ; a9
POLKADOT_BOW:	.dsb 1 ; aa
ITEM_AB:	.dsb 1 ; ab
UP_GRADE:	.dsb 1 ; ac
BERRY:		.dsb 1 ; ad
GOLD_BERRY:	.dsb 1 ; ae
SQUIRTBOTTLE:	.dsb 1 ; af
ITEM_B0:	.dsb 1 ; b0
PARK_BALL:	.dsb 1 ; b1
RAINBOW_WING:	.dsb 1 ; b2
ITEM_B3:	.dsb 1 ; b3
BRICK_PIECE:	.dsb 1 ; b4
SURF_MAIL:	.dsb 1 ; b5
LITEBLUEMAIL:	.dsb 1 ; b6
PORTRAITMAIL:	.dsb 1 ; b7
LOVELY_MAIL:	.dsb 1 ; b8
EON_MAIL:	.dsb 1 ; b9
MORPH_MAIL:	.dsb 1 ; ba
BLUESKY_MAIL:	.dsb 1 ; bb
MUSIC_MAIL:	.dsb 1 ; bc
MIRAGE_MAIL:	.dsb 1 ; bd
ITEM_BE:	.dsb 1 ; be
NORMAL_ITEMS_MAX:

NUM_ITEMS = NORMAL_ITEMS_MAX - 1

__tmhm_value__ = 1

; see data/moves/tmhm_moves.asm for moves
TM01 = NORMAL_ITEMS_MAX
TM_DYNAMICPUNCH:	.dsb 1 ; bf
__tmhm_value__ = __tmhm_value__ + 1
TM_HEADBUTT:		.dsb 1 ; c0
__tmhm_value__ = __tmhm_value__ + 1
TM_CURSE:		.dsb 1 ; c1
__tmhm_value__ = __tmhm_value__ + 1
TM_ROLLOUT:		.dsb 1 ; c2
__tmhm_value__ = __tmhm_value__ + 1
ITEM_C3:		.dsb 1 ; c3
TM_ROAR:		.dsb 1 ; c4
__tmhm_value__ = __tmhm_value__ + 1
TM_TOXIC:		.dsb 1 ; c5
__tmhm_value__ = __tmhm_value__ + 1
TM_ZAP_CANNON:		.dsb 1 ; c6
__tmhm_value__ = __tmhm_value__ + 1
TM_ROCK_SMASH:		.dsb 1 ; c7
__tmhm_value__ = __tmhm_value__ + 1
TM_PSYCH_UP:		.dsb 1 ; c8
__tmhm_value__ = __tmhm_value__ + 1
TM_HIDDEN_POWER:	.dsb 1 ; c9
__tmhm_value__ = __tmhm_value__ + 1
TM_SUNNY_DAY:		.dsb 1 ; ca
__tmhm_value__ = __tmhm_value__ + 1
TM_SWEET_SCENT:		.dsb 1 ; cb
__tmhm_value__ = __tmhm_value__ + 1
TM_SNORE:		.dsb 1 ; cc
__tmhm_value__ = __tmhm_value__ + 1
TM_BLIZZARD:		.dsb 1 ; cd
__tmhm_value__ = __tmhm_value__ + 1
TM_HYPER_BEAM:		.dsb 1 ; ce
__tmhm_value__ = __tmhm_value__ + 1
TM_ICY_WIND:		.dsb 1 ; cf
__tmhm_value__ = __tmhm_value__ + 1
TM_PROTECT:		.dsb 1 ; d0
__tmhm_value__ = __tmhm_value__ + 1
TM_RAIN_DANCE:		.dsb 1 ; d1
__tmhm_value__ = __tmhm_value__ + 1
TM_GIGA_DRAIN:		.dsb 1 ; d2
__tmhm_value__ = __tmhm_value__ + 1
TM_ENDURE:		.dsb 1 ; d3
__tmhm_value__ = __tmhm_value__ + 1
TM_FRUSTRATION:		.dsb 1 ; d4
__tmhm_value__ = __tmhm_value__ + 1
TM_SOLARBEAM:		.dsb 1 ; d5
__tmhm_value__ = __tmhm_value__ + 1
TM_IRON_TAIL:		.dsb 1 ; d6
__tmhm_value__ = __tmhm_value__ + 1
TM_DRAGONBREATH:	.dsb 1 ; d7
__tmhm_value__ = __tmhm_value__ + 1
TM_THUNDER:		.dsb 1 ; d8
__tmhm_value__ = __tmhm_value__ + 1
TM_EARTHQUAKE:		.dsb 1 ; d9
__tmhm_value__ = __tmhm_value__ + 1
TM_RETURN:		.dsb 1 ; da
__tmhm_value__ = __tmhm_value__ + 1
TM_DIG:			.dsb 1 ; db
__tmhm_value__ = __tmhm_value__ + 1
ITEM_DC:		.dsb 1 ; dc
TM_PSYCHIC_M:		.dsb 1 ; dd
__tmhm_value__ = __tmhm_value__ + 1
TM_SHADOW_BALL:		.dsb 1 ; de
__tmhm_value__ = __tmhm_value__ + 1
TM_MUD_SLAP:		.dsb 1 ; df
__tmhm_value__ = __tmhm_value__ + 1
TM_DOUBLE_TEAM:		.dsb 1 ; e0
__tmhm_value__ = __tmhm_value__ + 1
TM_ICE_PUNCH:		.dsb 1 ; e1
__tmhm_value__ = __tmhm_value__ + 1
TM_SWAGGER:		.dsb 1 ; e2
__tmhm_value__ = __tmhm_value__ + 1
TM_SLEEP_TALK:		.dsb 1 ; e3
__tmhm_value__ = __tmhm_value__ + 1
TM_SLUDGE_BOMB:		.dsb 1 ; e4
__tmhm_value__ = __tmhm_value__ + 1
TM_SANDSTORM:		.dsb 1 ; e5
__tmhm_value__ = __tmhm_value__ + 1
TM_FIRE_BLAST:		.dsb 1 ; e6
__tmhm_value__ = __tmhm_value__ + 1
TM_SWIFT:		.dsb 1 ; e7
__tmhm_value__ = __tmhm_value__ + 1
TM_DEFENSE_CURL:	.dsb 1 ; e8
__tmhm_value__ = __tmhm_value__ + 1
TM_THUNDERPUNCH:	.dsb 1 ; e9
__tmhm_value__ = __tmhm_value__ + 1
TM_DREAM_EATER:		.dsb 1 ; ea
__tmhm_value__ = __tmhm_value__ + 1
TM_DETECT:		.dsb 1 ; eb
__tmhm_value__ = __tmhm_value__ + 1
TM_REST:		.dsb 1 ; ec
__tmhm_value__ = __tmhm_value__ + 1
TM_ATTRACT:		.dsb 1 ; ed
__tmhm_value__ = __tmhm_value__ + 1
TM_THIEF:		.dsb 1 ; ee
__tmhm_value__ = __tmhm_value__ + 1
TM_STEEL_WING:		.dsb 1 ; ef
__tmhm_value__ = __tmhm_value__ + 1
TM_FIRE_PUNCH:		.dsb 1 ; f0
__tmhm_value__ = __tmhm_value__ + 1
TM_FURY_CUTTER:		.dsb 1 ; f1
__tmhm_value__ = __tmhm_value__ + 1
TM_NIGHTMARE:		.dsb 1 ; f2
__tmhm_value__ = __tmhm_value__ + 1
NUM_TMS = __tmhm_value__ - 1

HM01 = const_value
HM_CUT:		.dsb 1 ; f3
__tmhm_value__ = __tmhm_value__ + 1
HM_FLY:		.dsb 1 ; f4
__tmhm_value__ = __tmhm_value__ + 1
HM_SURF:	.dsb 1 ; f5
__tmhm_value__ = __tmhm_value__ + 1
HM_STRENGTH:	.dsb 1 ; f6
__tmhm_value__ = __tmhm_value__ + 1
HM_FLASH:	.dsb 1 ; f7
__tmhm_value__ = __tmhm_value__ + 1
HM_WHIRLPOOL:	.dsb 1 ; f8
__tmhm_value__ = __tmhm_value__ + 1
HM_WATERFALL:	.dsb 1 ; f9
__tmhm_value__ = __tmhm_value__ + 1
NUM_HMS = __tmhm_value__ - NUM_TMS - 1

NUM_TM_HM = NUM_TMS + NUM_HMS

ITEM_FA:	.dsb 1 ; fa
.ende

USE_SCRIPT_VAR = $00
ITEM_FROM_MEM  = $ff

; leftovers from red
SAFARI_BALL    = MOON_STONE
MOON_STONE_RED = BURN_HEAL
FULL_HEAL_RED  = X_SPEED