; object_struct members (see macros/ram.asm)
.enum 0
OBJECT_SPRITE:			.dsb 1 ;00
OBJECT_MAP_OBJECT_INDEX:	.dsb 1 ;01
OBJECT_SPRITE_TILE:		.dsb 1 ;02
OBJECT_MOVEMENT_TYPE:		.dsb 1 ;03
OBJECT_FLAGS1:			.dsb 1 ;04
OBJECT_FLAGS2:			.dsb 1 ;05
OBJECT_PALETTE:			.dsb 1 ;06
OBJECT_WALKING:			.dsb 1 ;07
OBJECT_DIRECTION:		.dsb 1 ;08
OBJECT_STEP_TYPE:		.dsb 1 ;09
OBJECT_STEP_DURATION:		.dsb 1 ;0a
OBJECT_ACTION:			.dsb 1 ;0b
OBJECT_STEP_FRAME:		.dsb 1 ;0c
OBJECT_FACING:			.dsb 1 ;0d
OBJECT_TILE:			.dsb 1 ;0e
OBJECT_LAST_TILE:		.dsb 1 ;0f
OBJECT_MAP_X:			.dsb 1 ;10
OBJECT_MAP_Y:			.dsb 1 ;11
OBJECT_LAST_MAP_X:		.dsb 1 ;12
OBJECT_LAST_MAP_Y:		.dsb 1 ;13
OBJECT_INIT_X:			.dsb 1 ;14
OBJECT_INIT_Y:			.dsb 1 ;15
OBJECT_RADIUS:			.dsb 1 ;16
OBJECT_SPRITE_X:		.dsb 1 ;17
OBJECT_SPRITE_Y:		.dsb 1 ;18
OBJECT_SPRITE_X_OFFSET:		.dsb 1 ;19
OBJECT_SPRITE_Y_OFFSET:		.dsb 1 ;1a
OBJECT_MOVEMENT_INDEX:		.dsb 1 ;1b
OBJECT_STEP_INDEX:		.dsb 1 ;1c
OBJECT_1D:			.dsb 1 ;1d
OBJECT_1E:			.dsb 1 ;1e
OBJECT_JUMP_HEIGHT:		.dsb 1 ;1f
OBJECT_RANGE:			.dsb 1 ;20
	.dsb 7
OBJECT_LENGTH:
.ende
NUM_OBJECT_STRUCTS = 13 ;see wObjectStructs

; object_struct OBJECT_DIRECTION values
OW_DOWN  = DOWN  << 2
OW_UP    = UP    << 2
OW_LEFT  = LEFT  << 2
OW_RIGHT = RIGHT << 2

; object_struct OBJECT_FLAGS1 bit flags
.enum 0
INVISIBLE_F:		.dsb 1 ; 0
WONT_DELETE_F:		.dsb 1 ; 1
FIXED_FACING_F:		.dsb 1 ; 2
SLIDING_F:		.dsb 1 ; 3
NOCLIP_TILES_F:		.dsb 1 ; 4
MOVE_ANYWHERE_F:	.dsb 1 ; 5
NOCLIP_OBJS_F:		.dsb 1 ; 6
EMOTE_OBJECT_F:		.dsb 1 ; 7
.ende

INVISIBLE     = 1 << INVISIBLE_F
WONT_DELETE   = 1 << WONT_DELETE_F
FIXED_FACING  = 1 << FIXED_FACING_F
SLIDING       = 1 << SLIDING_F
NOCLIP_TILES  = 1 << NOCLIP_TILES_F
MOVE_ANYWHERE = 1 << MOVE_ANYWHERE_F
NOCLIP_OBJS   = 1 << NOCLIP_OBJS_F
EMOTE_OBJECT  = 1 << EMOTE_OBJECT_F

; object_struct OBJECT_FLAGS2 bit flags
.enum 0
LOW_PRIORITY_F:		.dsb 1 ; 0
HIGH_PRIORITY_F:	.dsb 1 ; 1
OBJ_FLAGS2_2:		.dsb 1 ; 2
OVERHEAD_F:		.dsb 1 ; 3
USE_OBP1_F:		.dsb 1 ; 4
FROZEN_F:		.dsb 1 ; 5
OBJ_FLAGS2_6:		.dsb 1 ; 6
OBJ_FLAGS2_7:		.dsb 1 ; 7
.ende

LOW_PRIORITY  = 1 << LOW_PRIORITY_F
HIGH_PRIORITY = 1 << HIGH_PRIORITY_F
OVERHEAD      = 1 << OVERHEAD_F
USE_OBP1      = 1 << USE_OBP1_F

; object_struct OBJECT_PALETTE bit flags
.enum 5
SWIMMING_F:		.dsb 1 ; 5
STRENGTH_BOULDER_F:	.dsb 1 ; 6
BIG_OBJECT_F:		.dsb 1 ; 7
.ende

SWIMMING         = 1 << SWIMMING_F
STRENGTH_BOULDER = 1 << STRENGTH_BOULDER_F
BIG_OBJECT       = 1 << BIG_OBJECT_F

; facing attribute bit flags
RELATIVE_ATTRIBUTES_F = 1
ABSOLUTE_TILE_ID_F    = 2

RELATIVE_ATTRIBUTES = 1 << RELATIVE_ATTRIBUTES_F
ABSOLUTE_TILE_ID    = 1 << ABSOLUTE_TILE_ID_F

; map_object struct members (see macros/ram.asm)
; struct initialized by object_event macro (see macros/scripts/maps.asm)
.enum 0
MAPOBJECT_OBJECT_STRUCT_ID:	.dsb 1 ;0
MAPOBJECT_SPRITE:		.dsb 1 ;1
MAPOBJECT_Y_COORD:		.dsb 1 ;2
MAPOBJECT_X_COORD:		.dsb 1 ;3
MAPOBJECT_MOVEMENT:		.dsb 1 ;4
MAPOBJECT_RADIUS:		.dsb 1 ;5
MAPOBJECT_HOUR_1:		.dsb 1 ;6
MAPOBJECT_HOUR_2:
MAPOBJECT_TIMEOFDAY:		.dsb 1 ;7
MAPOBJECT_PALETTE:
MAPOBJECT_TYPE:			.dsb 1 ;8
MAPOBJECT_SIGHT_RANGE:		.dsb 1 ;9
MAPOBJECT_SCRIPT_POINTER:	.dsb 2 ;a
MAPOBJECT_EVENT_FLAG:		.dsb 2 ;c
	.dsb 2
MAPOBJECT_LENGTH:
NUM_OBJECTS = 16
PLAYER_OBJECT = 0
.ende

MAPOBJECT_PALETTE_MASK = %11110000
MAPOBJECT_TYPE_MASK    = %00001111

; SpriteMovementData struct members (see data/sprites/map_objects.asm)
.enum 0
SPRITEMOVEATTR_MOVEMENT:	.dsb 1 ;0
SPRITEMOVEATTR_FACING:		.dsb 1 ;1
SPRITEMOVEATTR_ACTION:		.dsb 1 ;2
SPRITEMOVEATTR_FLAGS1:		.dsb 1 ;3
SPRITEMOVEATTR_FLAGS2:		.dsb 1 ;4
SPRITEMOVEATTR_PALFLAGS:	.dsb 1 ;5
NUM_SPRITEMOVEDATA_FIELDS:
.ende

MAPOBJECT_SCREEN_WIDTH  = (SCREEN_WIDTH / 2) + 2
MAPOBJECT_SCREEN_HEIGHT = (SCREEN_HEIGHT / 2) + 2

; SpriteMovementData indexes (see data/sprites/map_objects.asm)
.enum 0
SPRITEMOVEDATA_00:			.dsb 1 ; 00
SPRITEMOVEDATA_STILL:			.dsb 1 ; 01
SPRITEMOVEDATA_WANDER:			.dsb 1 ; 02
SPRITEMOVEDATA_SPINRANDOM_SLOW:		.dsb 1 ; 03
SPRITEMOVEDATA_WALK_UP_DOWN:		.dsb 1 ; 04
SPRITEMOVEDATA_WALK_LEFT_RIGHT:		.dsb 1 ; 05
SPRITEMOVEDATA_STANDING_DOWN:		.dsb 1 ; 06
SPRITEMOVEDATA_STANDING_UP:		.dsb 1 ; 07
SPRITEMOVEDATA_STANDING_LEFT:		.dsb 1 ; 08
SPRITEMOVEDATA_STANDING_RIGHT:		.dsb 1 ; 09
SPRITEMOVEDATA_SPINRANDOM_FAST:		.dsb 1 ; 0a
SPRITEMOVEDATA_PLAYER:			.dsb 1 ; 0b
SPRITEMOVEDATA_INDEXED_1:		.dsb 1 ; 0c
SPRITEMOVEDATA_INDEXED_2:		.dsb 1 ; 0d
SPRITEMOVEDATA_0E:			.dsb 1 ; 0e
SPRITEMOVEDATA_0F:			.dsb 1 ; 0f
SPRITEMOVEDATA_10:			.dsb 1 ; 10
SPRITEMOVEDATA_11:			.dsb 1 ; 11
SPRITEMOVEDATA_12:			.dsb 1 ; 12
SPRITEMOVEDATA_FOLLOWING:		.dsb 1 ; 13
SPRITEMOVEDATA_SCRIPTED:		.dsb 1 ; 14
SPRITEMOVEDATA_BIGDOLLSYM:		.dsb 1 ; 15
SPRITEMOVEDATA_POKEMON:			.dsb 1 ; 16
SPRITEMOVEDATA_SUDOWOODO:		.dsb 1 ; 17
SPRITEMOVEDATA_SMASHABLE_ROCK:		.dsb 1 ; 18
SPRITEMOVEDATA_STRENGTH_BOULDER:	.dsb 1 ; 19
SPRITEMOVEDATA_FOLLOWNOTEXACT:		.dsb 1 ; 1a
SPRITEMOVEDATA_SHADOW:			.dsb 1 ; 1b
SPRITEMOVEDATA_EMOTE:			.dsb 1 ; 1c
SPRITEMOVEDATA_SCREENSHAKE:		.dsb 1 ; 1d
SPRITEMOVEDATA_SPINCOUNTERCLOCKWISE:	.dsb 1 ; 1e
SPRITEMOVEDATA_SPINCLOCKWISE:		.dsb 1 ; 1f
SPRITEMOVEDATA_BIGDOLLASYM:		.dsb 1 ; 20
SPRITEMOVEDATA_BIGDOLL:			.dsb 1 ; 21
SPRITEMOVEDATA_BOULDERDUST:		.dsb 1 ; 22
SPRITEMOVEDATA_GRASS:			.dsb 1 ; 23
SPRITEMOVEDATA_SWIM_WANDER:		.dsb 1 ; 24
NUM_SPRITEMOVEDATA:
.ende

; StepFunction_FromMovement.Pointers indexes (see engine/ove.dsb 2orld/map_objects.asm)
.enum 0
SPRITEMOVEFN_00:			.dsb 1 ; 00
SPRITEMOVEFN_RANDOM_WALK_Y:		.dsb 1 ; 01
SPRITEMOVEFN_RANDOM_WALK_X:		.dsb 1 ; 02
SPRITEMOVEFN_RANDOM_WALK_XY:		.dsb 1 ; 03
SPRITEMOVEFN_SLOW_RANDOM_SPIN:		.dsb 1 ; 04
SPRITEMOVEFN_FAST_RANDOM_SPIN:		.dsb 1 ; 05
SPRITEMOVEFN_STANDING:			.dsb 1 ; 06
SPRITEMOVEFN_OBEY_DPAD:			.dsb 1 ; 07
SPRITEMOVEFN_INDEXED_1:			.dsb 1 ; 08
SPRITEMOVEFN_INDEXED_2:			.dsb 1 ; 09
SPRITEMOVEFN_0A:			.dsb 1 ; 0a
SPRITEMOVEFN_0B:			.dsb 1 ; 0b
SPRITEMOVEFN_0C:			.dsb 1 ; 0c
SPRITEMOVEFN_0D:			.dsb 1 ; 0d
SPRITEMOVEFN_0E:			.dsb 1 ; 0e
SPRITEMOVEFN_FOLLOW:			.dsb 1 ; 0f
SPRITEMOVEFN_SCRIPTED:			.dsb 1 ; 10
SPRITEMOVEFN_STRENGTH:			.dsb 1 ; 11
SPRITEMOVEFN_FOLLOWNOTEXACT:		.dsb 1 ; 12
SPRITEMOVEFN_SHADOW:			.dsb 1 ; 13
SPRITEMOVEFN_EMOTE:			.dsb 1 ; 14
SPRITEMOVEFN_BIG_SNORLAX:		.dsb 1 ; 15
SPRITEMOVEFN_BOUNCE:			.dsb 1 ; 16
SPRITEMOVEFN_SCREENSHAKE:		.dsb 1 ; 17
SPRITEMOVEFN_SPIN_CLOCKWISE:		.dsb 1 ; 18
SPRITEMOVEFN_SPIN_COUNTERCLOCKWISE:	.dsb 1 ; 19
SPRITEMOVEFN_BOULDERDUST:		.dsb 1 ; 1a
SPRITEMOVEFN_GRASS:			.dsb 1 ; 1b
NUM_SPRITEMOVEFN:
.ende

; StepTypesJumptable indexes (see engine/ove.dsb 2orld/map_objects.asm)
.enum 0
STEP_TYPE_RESET:		.dsb 1 ; 00
STEP_TYPE_FROM_MOVEMENT:	.dsb 1 ; 01
STEP_TYPE_NPC_WALK:		.dsb 1 ; 02
STEP_TYPE_SLEEP:		.dsb 1 ; 03
STEP_TYPE_STANDING:		.dsb 1 ; 04
STEP_TYPE_RESTORE:		.dsb 1 ; 05
STEP_TYPE_PLAYER_WALK:		.dsb 1 ; 06
STEP_TYPE_CONTINUE_WALK:	.dsb 1 ; 07
STEP_TYPE_NPC_JUMP:		.dsb 1 ; 08
STEP_TYPE_PLAYER_JUMP:		.dsb 1 ; 09
STEP_TYPE_TURN:			.dsb 1 ; 0a
STEP_TYPE_BUMP:			.dsb 1 ; 0b
STEP_TYPE_TELEPORT_FROM:	.dsb 1 ; 0c
STEP_TYPE_TELEPORT_TO:		.dsb 1 ; 0d
STEP_TYPE_SKYFALL:		.dsb 1 ; 0e
STEP_TYPE_STRENGTH_BOULDER:	.dsb 1 ; 0f
STEP_TYPE_GOT_BITE:		.dsb 1 ; 10
STEP_TYPE_ROCK_SMASH:		.dsb 1 ; 11
STEP_TYPE_RETURN_DIG:		.dsb 1 ; 12
STEP_TYPE_TRACKING_OBJECT:	.dsb 1 ; 13
STEP_TYPE_14:			.dsb 1 ; 14
STEP_TYPE_SCREENSHAKE:		.dsb 1 ; 15
STEP_TYPE_16:			.dsb 1 ; 16
STEP_TYPE_17:			.dsb 1 ; 17
STEP_TYPE_DELETE:		.dsb 1 ; 18
NUM_STEP_TYPES:
.ende

; ObjectActionPairPointers indexes (see engine/ove.dsb 2orld/map_object_action.asm)
.enum 0
OBJECT_ACTION_00:		.dsb 1 ; 00
OBJECT_ACTION_STAND:		.dsb 1 ; 01
OBJECT_ACTION_STEP:		.dsb 1 ; 02
OBJECT_ACTION_BUMP:		.dsb 1 ; 03
OBJECT_ACTION_SPIN:		.dsb 1 ; 04
OBJECT_ACTION_SPIN_FLICKER:	.dsb 1 ; 05
OBJECT_ACTION_FISHING:		.dsb 1 ; 06
OBJECT_ACTION_SHADOW:		.dsb 1 ; 07
OBJECT_ACTION_EMOTE:		.dsb 1 ; 08
OBJECT_ACTION_BIG_DOLL_SYM:	.dsb 1 ; 09
OBJECT_ACTION_BOUNCE:		.dsb 1 ; 0a
OBJECT_ACTION_WEIRD_TREE:	.dsb 1 ; 0b
OBJECT_ACTION_BIG_DOLL_ASYM:	.dsb 1 ; 0c
OBJECT_ACTION_BIG_DOLL:		.dsb 1 ; 0d
OBJECT_ACTION_BOULDER_DUST:	.dsb 1 ; 0e
OBJECT_ACTION_GRASS_SHAKE:	.dsb 1 ; 0f
NUM_OBJECT_ACTIONS:
.ende

; Facings indexes (see data/sprites/facings.asm)
.enum 0
FACING_STEP_DOWN_0:	.dsb 1 ; 00
FACING_STEP_DOWN_1:	.dsb 1 ; 01
FACING_STEP_DOWN_2:	.dsb 1 ; 02
FACING_STEP_DOWN_3:	.dsb 1 ; 03
FACING_STEP_UP_0:	.dsb 1 ; 04
FACING_STEP_UP_1:	.dsb 1 ; 05
FACING_STEP_UP_2:	.dsb 1 ; 06
FACING_STEP_UP_3:	.dsb 1 ; 07
FACING_STEP_LEFT_0:	.dsb 1 ; 08
FACING_STEP_LEFT_1:	.dsb 1 ; 09
FACING_STEP_LEFT_2:	.dsb 1 ; 0a
FACING_STEP_LEFT_3:	.dsb 1 ; 0b
FACING_STEP_RIGHT_0:	.dsb 1 ; 0c
FACING_STEP_RIGHT_1:	.dsb 1 ; 0d
FACING_STEP_RIGHT_2:	.dsb 1 ; 0e
FACING_STEP_RIGHT_3:	.dsb 1 ; 0f
FACING_FISH_DOWN:	.dsb 1 ; 10
FACING_FISH_UP:		.dsb 1 ; 11
FACING_FISH_LEFT:	.dsb 1 ; 12
FACING_FISH_RIGHT:	.dsb 1 ; 13
FACING_EMOTE:		.dsb 1 ; 14
FACING_SHADOW:		.dsb 1 ; 15
FACING_BIG_DOLL_ASYM:	.dsb 1 ; 16
FACING_BIG_DOLL_SYM:	.dsb 1 ; 17
FACING_WEIRD_TREE_0:	.dsb 1 ; 18
FACING_WEIRD_TREE_1:	.dsb 1 ; 19
FACING_WEIRD_TREE_2:	.dsb 1 ; 1a
FACING_WEIRD_TREE_3:	.dsb 1 ; 1b
FACING_BOULDER_DUST_1:	.dsb 1 ; 1c
FACING_BOULDER_DUST_2:	.dsb 1 ; 1d
FACING_GRASS_1:		.dsb 1 ; 1e
FACING_GRASS_2:		.dsb 1 ; 1f
NUM_FACINGS:
.ende

; DoPlayerMovement.DoStep arguments (see engine/ove.dsb 2orld/player_movement.asm)
.enum 0
STEP_SLOW:		.dsb 1 ; 0
STEP_WALK:		.dsb 1 ; 1
STEP_BIKE:		.dsb 1 ; 2
STEP_LEDGE:		.dsb 1 ; 3
STEP_ICE:		.dsb 1 ; 4
STEP_TURN:		.dsb 1 ; 5
STEP_BACK_LEDGE:	.dsb 1 ; 6
STEP_WALK_IN_PLACE:	.dsb 1 ; 7
NUM_STEPS:
.ende
