PLAYER_NORMAL    = 0
PLAYER_BIKE      = 1
PLAYER_SKATE     = 2
PLAYER_SURF      = 4
PLAYER_SURF_PIKA = 8

NAMETABLE_ATTRIBUTE_0 = $23c0

TEXT_DELAY_MASK = %111
.enum 4
NO_TEXT_SCROLL:	.dsb 1
	.dsb 1
BATTLE_SHIFT:	.dsb 1
BATTLE_SCENE:
.ende

NUM_TM_HM = 50 + 7

.enum 0
BOX_COUNT:	.dsb 1
BOX_SPECIES:	.dsb MONS_PER_BOX
BOX_MON_1:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_2:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_3:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_4:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_5:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_6:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_7:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_8:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_9:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_10:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_11:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_12:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_13:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_14:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_15:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_16:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_17:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_18:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_19:	.dsb BOXMON_STRUCT_LENGTH
BOX_MON_20:	.dsb BOXMON_STRUCT_LENGTH
.ende
