; song ids
; Music indexes (see audio/music_pointers.asm)
.enum 0
MUSIC_NONE:				.dsb 1 ; 00
MUSIC_TITLE:				.dsb 1 ; 01
MUSIC_ROUTE_1:				.dsb 1 ; 02
MUSIC_ROUTE_3:				.dsb 1 ; 03
MUSIC_ROUTE_12:				.dsb 1 ; 04
MUSIC_MAGNET_TRAIN:			.dsb 1 ; 05
MUSIC_KANTO_GYM_LEADER_BATTLE:		.dsb 1 ; 06
MUSIC_KANTO_TRAINER_BATTLE:		.dsb 1 ; 07
MUSIC_KANTO_WILD_BATTLE:		.dsb 1 ; 08
MUSIC_POKEMON_CENTER:			.dsb 1 ; 09
MUSIC_HIKER_ENCOUNTER:			.dsb 1 ; 0a
MUSIC_LASS_ENCOUNTER:			.dsb 1 ; 0b
MUSIC_OFFICER_ENCOUNTER:		.dsb 1 ; 0c
MUSIC_HEAL:				.dsb 1 ; 0d
MUSIC_LAVENDER_TOWN:			.dsb 1 ; 0e
MUSIC_ROUTE_2:				.dsb 1 ; 0f
MUSIC_MT_MOON:				.dsb 1 ; 10
MUSIC_SHOW_ME_AROUND:			.dsb 1 ; 11
MUSIC_GAME_CORNER:			.dsb 1 ; 12
MUSIC_BICYCLE:				.dsb 1 ; 13
MUSIC_HALL_OF_FAME:			.dsb 1 ; 14
MUSIC_VIRIDIAN_CITY:			.dsb 1 ; 15
MUSIC_CELADON_CITY:			.dsb 1 ; 16
MUSIC_TRAINER_VICTORY:			.dsb 1 ; 17
MUSIC_WILD_VICTORY:			.dsb 1 ; 18
MUSIC_GYM_VICTORY:			.dsb 1 ; 19
MUSIC_MT_MOON_SQUARE:			.dsb 1 ; 1a
MUSIC_GYM:				.dsb 1 ; 1b
MUSIC_PALLET_TOWN:			.dsb 1 ; 1c
MUSIC_POKEMON_TALK:			.dsb 1 ; 1d
MUSIC_PROF_OAK:				.dsb 1 ; 1e
MUSIC_RIVAL_ENCOUNTER:			.dsb 1 ; 1f
MUSIC_RIVAL_AFTER:			.dsb 1 ; 20
MUSIC_SURF:				.dsb 1 ; 21
MUSIC_EVOLUTION:			.dsb 1 ; 22
MUSIC_NATIONAL_PARK:			.dsb 1 ; 23
MUSIC_CREDITS:				.dsb 1 ; 24
MUSIC_AZALEA_TOWN:			.dsb 1 ; 25
MUSIC_CHERRYGROVE_CITY:			.dsb 1 ; 26
MUSIC_KIMONO_ENCOUNTER:			.dsb 1 ; 27
MUSIC_UNION_CAVE:			.dsb 1 ; 28
MUSIC_JOHTO_WILD_BATTLE:		.dsb 1 ; 29
MUSIC_JOHTO_TRAINER_BATTLE:		.dsb 1 ; 2a
MUSIC_ROUTE_30:				.dsb 1 ; 2b
MUSIC_ECRUTEAK_CITY:			.dsb 1 ; 2c
MUSIC_VIOLET_CITY:			.dsb 1 ; 2d
MUSIC_JOHTO_GYM_LEADER_BATTLE:		.dsb 1 ; 2e
MUSIC_CHAMPION_BATTLE:			.dsb 1 ; 2f
MUSIC_RIVAL_BATTLE:			.dsb 1 ; 30
MUSIC_ROCKET_BATTLE:			.dsb 1 ; 31
MUSIC_PROF_ELM:				.dsb 1 ; 32
MUSIC_DARK_CAVE:			.dsb 1 ; 33
MUSIC_ROUTE_29:				.dsb 1 ; 34
MUSIC_ROUTE_36:				.dsb 1 ; 35
MUSIC_SS_AQUA:				.dsb 1 ; 36
MUSIC_YOUNGSTER_ENCOUNTER:		.dsb 1 ; 37
MUSIC_BEAUTY_ENCOUNTER:			.dsb 1 ; 38
MUSIC_ROCKET_ENCOUNTER:			.dsb 1 ; 39
MUSIC_POKEMANIAC_ENCOUNTER:		.dsb 1 ; 3a
MUSIC_SAGE_ENCOUNTER:			.dsb 1 ; 3b
MUSIC_NEW_BARK_TOWN:			.dsb 1 ; 3c
MUSIC_GOLDENROD_CITY:			.dsb 1 ; 3d
MUSIC_VERMILION_CITY:			.dsb 1 ; 3e
MUSIC_POKEMON_CHANNEL:			.dsb 1 ; 3f
MUSIC_POKE_FLUTE_CHANNEL:		.dsb 1 ; 40
MUSIC_TIN_TOWER:			.dsb 1 ; 41
MUSIC_SPROUT_TOWER:			.dsb 1 ; 42
MUSIC_BURNED_TOWER:			.dsb 1 ; 43
MUSIC_LIGHTHOUSE:			.dsb 1 ; 44
MUSIC_LAKE_OF_RAGE:			.dsb 1 ; 45
MUSIC_INDIGO_PLATEAU:			.dsb 1 ; 46
MUSIC_ROUTE_37:				.dsb 1 ; 47
MUSIC_ROCKET_HIDEOUT:			.dsb 1 ; 48
MUSIC_DRAGONS_DEN:			.dsb 1 ; 49
MUSIC_JOHTO_WILD_BATTLE_NIGHT:		.dsb 1 ; 4a
MUSIC_RUINS_OF_ALPH_RADIO:		.dsb 1 ; 4b
MUSIC_CAPTURE:				.dsb 1 ; 4c
MUSIC_ROUTE_26:				.dsb 1 ; 4d
MUSIC_MOM:				.dsb 1 ; 4e
MUSIC_VICTORY_ROAD:			.dsb 1 ; 4f
MUSIC_POKEMON_LULLABY:			.dsb 1 ; 50
MUSIC_POKEMON_MARCH:			.dsb 1 ; 51
MUSIC_GS_OPENING:			.dsb 1 ; 52
MUSIC_GS_OPENING_2:			.dsb 1 ; 53
MUSIC_MAIN_MENU:			.dsb 1 ; 54
MUSIC_RUINS_OF_ALPH_INTERIOR:		.dsb 1 ; 55
MUSIC_ROCKET_OVERTURE:			.dsb 1 ; 56
MUSIC_DANCING_HALL:			.dsb 1 ; 57
MUSIC_BUG_CATCHING_CONTEST_RANKING:	.dsb 1 ; 58
MUSIC_BUG_CATCHING_CONTEST:		.dsb 1 ; 59
MUSIC_LAKE_OF_RAGE_ROCKET_RADIO:	.dsb 1 ; 5a
MUSIC_PRINTER:				.dsb 1 ; 5b
MUSIC_POST_CREDITS:			.dsb 1 ; 5c
NUM_MUSIC_SONGS:
.ende

; GetMapMusic picks music for this value (see home/map.asm)
MUSIC_MAHOGANY_MART = $64

; ExitPokegearRadio_HandleMusic uses these values
RESTART_MAP_MUSIC = $fe
ENTER_MAP_MUSIC   = $ff

; GetMapMusic picks music for this bit flag
RADIO_TOWER_MUSIC_F = 7
RADIO_TOWER_MUSIC = 1 << RADIO_TOWER_MUSIC_F
