; pokemon ids
; indexes for:
; - PokemonNames (see data/pokemon/names.asm)
; - BaseData (see data/pokemon/base_stats.asm)
; - EvosAttacksPointers (see data/pokemon/evos_attacks_pointers.asm)
; - EggMovePointers (see data/pokemon/egg_move_pointers.asm)
; - PokemonCries (see data/pokemon/cries.asm)
; - MonMenuIcons (see data/pokemon/menu_icons.asm)
; - PokemonPicPointers (see data/pokemon/pic_pointers.asm)
; - PokemonPalettes (see data/pokemon/palettes.asm)
; - PokedexDataPointerTable (see data/pokemon/dex_entry_pointers.asm)
; - AlphabeticalPokedexOrder (see data/pokemon/dex_order_alpha.asm)
; - NewPokedexOrder (see data/pokemon/dex_order_new.asm)
; - Pokered_MonIndices (see data/pokemon/gen1_order.asm)
; - Footprints (see gfx/footprints.asm)
.enum 1
BULBASAUR:	.dsb 1 ; 01
IVYSAUR:	.dsb 1 ; 02
VENUSAUR:	.dsb 1 ; 03
CHARMANDER:	.dsb 1 ; 04
CHARMELEON:	.dsb 1 ; 05
CHARIZARD:	.dsb 1 ; 06
SQUIRTLE:	.dsb 1 ; 07
WARTORTLE:	.dsb 1 ; 08
BLASTOISE:	.dsb 1 ; 09
CATERPIE:	.dsb 1 ; 0a
METAPOD:	.dsb 1 ; 0b
BUTTERFREE:	.dsb 1 ; 0c
WEEDLE:		.dsb 1 ; 0d
KAKUNA:		.dsb 1 ; 0e
BEEDRILL:	.dsb 1 ; 0f
PIDGEY:		.dsb 1 ; 10
PIDGEOTTO:	.dsb 1 ; 11
PIDGEOT:	.dsb 1 ; 12
RATTATA:	.dsb 1 ; 13
RATICATE:	.dsb 1 ; 14
SPEAROW:	.dsb 1 ; 15
FEAROW:		.dsb 1 ; 16
EKANS:		.dsb 1 ; 17
ARBOK:		.dsb 1 ; 18
PIKACHU:	.dsb 1 ; 19
RAICHU:		.dsb 1 ; 1a
SANDSHREW:	.dsb 1 ; 1b
SANDSLASH:	.dsb 1 ; 1c
NIDORAN_F:	.dsb 1 ; 1d
NIDORINA:	.dsb 1 ; 1e
NIDOQUEEN:	.dsb 1 ; 1f
NIDORAN_M:	.dsb 1 ; 20
NIDORINO:	.dsb 1 ; 21
NIDOKING:	.dsb 1 ; 22
CLEFAIRY:	.dsb 1 ; 23
CLEFABLE:	.dsb 1 ; 24
VULPIX:		.dsb 1 ; 25
NINETALES:	.dsb 1 ; 26
JIGGLYPUFF:	.dsb 1 ; 27
WIGGLYTUFF:	.dsb 1 ; 28
ZUBAT:		.dsb 1 ; 29
GOLBAT:		.dsb 1 ; 2a
ODDISH:		.dsb 1 ; 2b
GLOOM:		.dsb 1 ; 2c
VILEPLUME:	.dsb 1 ; 2d
PARAS:		.dsb 1 ; 2e
PARASECT:	.dsb 1 ; 2f
VENONAT:	.dsb 1 ; 30
VENOMOTH:	.dsb 1 ; 31
DIGLETT:	.dsb 1 ; 32
DUGTRIO:	.dsb 1 ; 33
MEOWTH:		.dsb 1 ; 34
PERSIAN:	.dsb 1 ; 35
PSYDUCK:	.dsb 1 ; 36
GOLDUCK:	.dsb 1 ; 37
MANKEY:		.dsb 1 ; 38
PRIMEAPE:	.dsb 1 ; 39
GROWLITHE:	.dsb 1 ; 3a
ARCANINE:	.dsb 1 ; 3b
POLIWAG:	.dsb 1 ; 3c
POLIWHIRL:	.dsb 1 ; 3d
POLIWRATH:	.dsb 1 ; 3e
ABRA:		.dsb 1 ; 3f
KADABRA:	.dsb 1 ; 40
ALAKAZAM:	.dsb 1 ; 41
MACHOP:		.dsb 1 ; 42
MACHOKE:	.dsb 1 ; 43
MACHAMP:	.dsb 1 ; 44
BELLSPROUT:	.dsb 1 ; 45
WEEPINBELL:	.dsb 1 ; 46
VICTREEBEL:	.dsb 1 ; 47
TENTACOOL:	.dsb 1 ; 48
TENTACRUEL:	.dsb 1 ; 49
GEODUDE:	.dsb 1 ; 4a
GRAVELER:	.dsb 1 ; 4b
GOLEM:		.dsb 1 ; 4c
PONYTA:		.dsb 1 ; 4d
RAPIDASH:	.dsb 1 ; 4e
SLOWPOKE:	.dsb 1 ; 4f
SLOWBRO:	.dsb 1 ; 50
MAGNEMITE:	.dsb 1 ; 51
MAGNETON:	.dsb 1 ; 52
FARFETCH_D:	.dsb 1 ; 53
DODUO:		.dsb 1 ; 54
DODRIO:		.dsb 1 ; 55
SEEL:		.dsb 1 ; 56
DEWGONG:	.dsb 1 ; 57
GRIMER:		.dsb 1 ; 58
MUK:		.dsb 1 ; 59
SHELLDER:	.dsb 1 ; 5a
CLOYSTER:	.dsb 1 ; 5b
GASTLY:		.dsb 1 ; 5c
HAUNTER:	.dsb 1 ; 5d
GENGAR:		.dsb 1 ; 5e
ONIX:		.dsb 1 ; 5f
DROWZEE:	.dsb 1 ; 60
HYPNO:		.dsb 1 ; 61
KRABBY:		.dsb 1 ; 62
KINGLER:	.dsb 1 ; 63
VOLTORB:	.dsb 1 ; 64
ELECTRODE:	.dsb 1 ; 65
EXEGGCUTE:	.dsb 1 ; 66
EXEGGUTOR:	.dsb 1 ; 67
CUBONE:		.dsb 1 ; 68
MAROWAK:	.dsb 1 ; 69
HITMONLEE:	.dsb 1 ; 6a
HITMONCHAN:	.dsb 1 ; 6b
LICKITUNG:	.dsb 1 ; 6c
KOFFING:	.dsb 1 ; 6d
WEEZING:	.dsb 1 ; 6e
RHYHORN:	.dsb 1 ; 6f
RHYDON:		.dsb 1 ; 70
CHANSEY:	.dsb 1 ; 71
TANGELA:	.dsb 1 ; 72
KANGASKHAN:	.dsb 1 ; 73
HORSEA:		.dsb 1 ; 74
SEADRA:		.dsb 1 ; 75
GOLDEEN:	.dsb 1 ; 76
SEAKING:	.dsb 1 ; 77
STARYU:		.dsb 1 ; 78
STARMIE:	.dsb 1 ; 79
MR__MIME:	.dsb 1 ; 7a
SCYTHER:	.dsb 1 ; 7b
JYNX:		.dsb 1 ; 7c
ELECTABUZZ:	.dsb 1 ; 7d
MAGMAR:		.dsb 1 ; 7e
PINSIR:		.dsb 1 ; 7f
TAUROS:		.dsb 1 ; 80
MAGIKARP:	.dsb 1 ; 81
GYARADOS:	.dsb 1 ; 82
LAPRAS:		.dsb 1 ; 83
DITTO:		.dsb 1 ; 84
EEVEE:		.dsb 1 ; 85
VAPOREON:	.dsb 1 ; 86
JOLTEON:	.dsb 1 ; 87
FLAREON:	.dsb 1 ; 88
PORYGON:	.dsb 1 ; 89
OMANYTE:	.dsb 1 ; 8a
OMASTAR:	.dsb 1 ; 8b
KABUTO:		.dsb 1 ; 8c
KABUTOPS:	.dsb 1 ; 8d
AERODACTYL:	.dsb 1 ; 8e
SNORLAX:	.dsb 1 ; 8f
ARTICUNO:	.dsb 1 ; 90
ZAPDOS:		.dsb 1 ; 91
MOLTRES:	.dsb 1 ; 92
DRATINI:	.dsb 1 ; 93
DRAGONAIR:	.dsb 1 ; 94
DRAGONITE:	.dsb 1 ; 95
MEWTWO:		.dsb 1 ; 96
MEW:		.dsb 1 ; 97
JOHTO_POKEMON:
CHIKORITA:	.dsb 1 ; 98
BAYLEEF:	.dsb 1 ; 99
MEGANIUM:	.dsb 1 ; 9a
CYNDAQUIL:	.dsb 1 ; 9b
QUILAVA:	.dsb 1 ; 9c
TYPHLOSION:	.dsb 1 ; 9d
TOTODILE:	.dsb 1 ; 9e
CROCONAW:	.dsb 1 ; 9f
FERALIGATR:	.dsb 1 ; a0
SENTRET:	.dsb 1 ; a1
FURRET:		.dsb 1 ; a2
HOOTHOOT:	.dsb 1 ; a3
NOCTOWL:	.dsb 1 ; a4
LEDYBA:		.dsb 1 ; a5
LEDIAN:		.dsb 1 ; a6
SPINARAK:	.dsb 1 ; a7
ARIADOS:	.dsb 1 ; a8
CROBAT:		.dsb 1 ; a9
CHINCHOU:	.dsb 1 ; aa
LANTURN:	.dsb 1 ; ab
PICHU:		.dsb 1 ; ac
CLEFFA:		.dsb 1 ; ad
IGGLYBUFF:	.dsb 1 ; ae
TOGEPI:		.dsb 1 ; af
TOGETIC:	.dsb 1 ; b0
NATU:		.dsb 1 ; b1
XATU:		.dsb 1 ; b2
MAREEP:		.dsb 1 ; b3
FLAAFFY:	.dsb 1 ; b4
AMPHAROS:	.dsb 1 ; b5
BELLOSSOM:	.dsb 1 ; b6
MARILL:		.dsb 1 ; b7
AZUMARILL:	.dsb 1 ; b8
SUDOWOODO:	.dsb 1 ; b9
POLITOED:	.dsb 1 ; ba
HOPPIP:		.dsb 1 ; bb
SKIPLOOM:	.dsb 1 ; bc
JUMPLUFF:	.dsb 1 ; bd
AIPOM:		.dsb 1 ; be
SUNKERN:	.dsb 1 ; bf
SUNFLORA:	.dsb 1 ; c0
YANMA:		.dsb 1 ; c1
WOOPER:		.dsb 1 ; c2
QUAGSIRE:	.dsb 1 ; c3
ESPEON:		.dsb 1 ; c4
UMBREON:	.dsb 1 ; c5
MURKROW:	.dsb 1 ; c6
SLOWKING:	.dsb 1 ; c7
MISDREAVUS:	.dsb 1 ; c8
UNOWN:		.dsb 1 ; c9
WOBBUFFET:	.dsb 1 ; ca
GIRAFARIG:	.dsb 1 ; cb
PINECO:		.dsb 1 ; cc
FORRETRESS:	.dsb 1 ; cd
DUNSPARCE:	.dsb 1 ; ce
GLIGAR:		.dsb 1 ; cf
STEELIX:	.dsb 1 ; d0
SNUBBULL:	.dsb 1 ; d1
GRANBULL:	.dsb 1 ; d2
QWILFISH:	.dsb 1 ; d3
SCIZOR:		.dsb 1 ; d4
SHUCKLE:	.dsb 1 ; d5
HERACROSS:	.dsb 1 ; d6
SNEASEL:	.dsb 1 ; d7
TEDDIURSA:	.dsb 1 ; d8
URSARING:	.dsb 1 ; d9
SLUGMA:		.dsb 1 ; da
MAGCARGO:	.dsb 1 ; db
SWINUB:		.dsb 1 ; dc
PILOSWINE:	.dsb 1 ; dd
CORSOLA:	.dsb 1 ; de
REMORAID:	.dsb 1 ; df
OCTILLERY:	.dsb 1 ; e0
DELIBIRD:	.dsb 1 ; e1
MANTINE:	.dsb 1 ; e2
SKARMORY:	.dsb 1 ; e3
HOUNDOUR:	.dsb 1 ; e4
HOUNDOOM:	.dsb 1 ; e5
KINGDRA:	.dsb 1 ; e6
PHANPY:		.dsb 1 ; e7
DONPHAN:	.dsb 1 ; e8
PORYGON2:	.dsb 1 ; e9
STANTLER:	.dsb 1 ; ea
SMEARGLE:	.dsb 1 ; eb
TYROGUE:	.dsb 1 ; ec
HITMONTOP:	.dsb 1 ; ed
SMOOCHUM:	.dsb 1 ; ee
ELEKID:		.dsb 1 ; ef
MAGBY:		.dsb 1 ; f0
MILTANK:	.dsb 1 ; f1
BLISSEY:	.dsb 1 ; f2
RAIKOU:		.dsb 1 ; f3
ENTEI:		.dsb 1 ; f4
SUICUNE:	.dsb 1 ; f5
LARVITAR:	.dsb 1 ; f6
PUPITAR:	.dsb 1 ; f7
TYRANITAR:	.dsb 1 ; f8
LUGIA:		.dsb 1 ; f9
HO_OH:		.dsb 1 ; fa
CELEBI:		.dsb 1 ; fb
POKEMON_END:
NUM_POKEMON = POKEMON_END - 1
		.dsb 1
EGG:		.dsb 1 ; fd
.ende

; Unown forms
; indexes for:
; - UnownWords (see data/pokemon/unown_words.asm)
; - UnownPicPointers (see data/pokemon/unown_pic_pointers.asm)
; - UnownAnimationPointers (see gfx/pokemon/unown_anim_pointers.asm)
; - UnownAnimationIdlePointers (see gfx/pokemon/unown_idle_pointers.asm)
; - UnownBitmasksPointers (see gfx/pokemon/unown_bitmask_pointers.asm)
; - UnownFramesPointers (see gfx/pokemon/unown_frame_pointers.asm)
.enum 1
UNOWN_A:	.dsb 1 ;  1
UNOWN_B:	.dsb 1 ;  2
UNOWN_C:	.dsb 1 ;  3
UNOWN_D:	.dsb 1 ;  4
UNOWN_E:	.dsb 1 ;  5
UNOWN_F:	.dsb 1 ;  6
UNOWN_G:	.dsb 1 ;  7
UNOWN_H:	.dsb 1 ;  8
UNOWN_I:	.dsb 1 ;  9
UNOWN_J:	.dsb 1 ; 10
UNOWN_K:	.dsb 1 ; 11
UNOWN_L:	.dsb 1 ; 12
UNOWN_M:	.dsb 1 ; 13
UNOWN_N:	.dsb 1 ; 14
UNOWN_O:	.dsb 1 ; 15
UNOWN_P:	.dsb 1 ; 16
UNOWN_Q:	.dsb 1 ; 17
UNOWN_R:	.dsb 1 ; 18
UNOWN_S:	.dsb 1 ; 19
UNOWN_T:	.dsb 1 ; 20
UNOWN_U:	.dsb 1 ; 21
UNOWN_V:	.dsb 1 ; 22
UNOWN_W:	.dsb 1 ; 23
UNOWN_X:	.dsb 1 ; 24
UNOWN_Y:	.dsb 1 ; 25
UNOWN_Z:	.dsb 1 ; 26
UNOWN_END:
NUM_UNOWN = UNOWN_END - 1 ; 26
.ende
