; SFX indexes (see audio/sfx_pointers.asm)
.enum 0
SFX_DEX_FANFARE_50_79:			.dsb 1 ; 00
SFX_ITEM:				.dsb 1 ; 01
SFX_CAUGHT_MON:				.dsb 1 ; 02
SFX_POKEBALLS_PLACED_ON_TABLE:		.dsb 1 ; 03
SFX_POTION:				.dsb 1 ; 04
SFX_FULL_HEAL:				.dsb 1 ; 05
SFX_MENU:				.dsb 1 ; 06
SFX_READ_TEXT:				.dsb 1 ; 07
SFX_READ_TEXT_2:			.dsb 1 ; 08
SFX_DEX_FANFARE_20_49:			.dsb 1 ; 09
SFX_DEX_FANFARE_80_109:			.dsb 1 ; 0a
SFX_POISON:				.dsb 1 ; 0b
SFX_GOT_SAFARI_BALLS:			.dsb 1 ; 0c
SFX_BOOT_PC:				.dsb 1 ; 0d
SFX_SHUT_DOWN_PC:			.dsb 1 ; 0e
SFX_CHOOSE_PC_OPTION:			.dsb 1 ; 0f
SFX_ESCAPE_ROPE:			.dsb 1 ; 10
SFX_PUSH_BUTTON:			.dsb 1 ; 11
SFX_SECOND_PART_OF_ITEMFINDER:		.dsb 1 ; 12
SFX_WARP_TO:				.dsb 1 ; 13
SFX_WARP_FROM:				.dsb 1 ; 14
SFX_CHANGE_DEX_MODE:			.dsb 1 ; 15
SFX_JUMP_OVER_LEDGE:			.dsb 1 ; 16
SFX_GRASS_RUSTLE:			.dsb 1 ; 17
SFX_FLY:				.dsb 1 ; 18
SFX_WRONG:				.dsb 1 ; 19
SFX_SQUEAK:				.dsb 1 ; 1a
SFX_STRENGTH:				.dsb 1 ; 1b
SFX_BOAT:				.dsb 1 ; 1c
SFX_WALL_OPEN:				.dsb 1 ; 1d
SFX_PLACE_PUZZLE_PIECE_DOWN:		.dsb 1 ; 1e
SFX_ENTER_DOOR:				.dsb 1 ; 1f
SFX_SWITCH_POKEMON:			.dsb 1 ; 20
SFX_TALLY:				.dsb 1 ; 21
SFX_TRANSACTION:			.dsb 1 ; 22
SFX_EXIT_BUILDING:			.dsb 1 ; 23
SFX_BUMP:				.dsb 1 ; 24
SFX_SAVE:				.dsb 1 ; 25
SFX_POKEFLUTE:				.dsb 1 ; 26
SFX_ELEVATOR_END:			.dsb 1 ; 27
SFX_THROW_BALL:				.dsb 1 ; 28
SFX_BALL_POOF:				.dsb 1 ; 29
SFX_FAINT:				.dsb 1 ; 2a
SFX_RUN:				.dsb 1 ; 2b
SFX_SLOT_MACHINE_START:			.dsb 1 ; 2c
SFX_FANFARE:				.dsb 1 ; 2d
SFX_PECK:				.dsb 1 ; 2e
SFX_KINESIS:				.dsb 1 ; 2f
SFX_LICK:				.dsb 1 ; 30
SFX_POUND:				.dsb 1 ; 31
SFX_MOVE_PUZZLE_PIECE:			.dsb 1 ; 32
SFX_COMET_PUNCH:			.dsb 1 ; 33
SFX_MEGA_PUNCH:				.dsb 1 ; 34
SFX_SCRATCH:				.dsb 1 ; 35
SFX_VICEGRIP:				.dsb 1 ; 36
SFX_RAZOR_WIND:				.dsb 1 ; 37
SFX_CUT:				.dsb 1 ; 38
SFX_WING_ATTACK:			.dsb 1 ; 39
SFX_WHIRLWIND:				.dsb 1 ; 3a
SFX_BIND:				.dsb 1 ; 3b
SFX_VINE_WHIP:				.dsb 1 ; 3c
SFX_DOUBLE_KICK:			.dsb 1 ; 3d
SFX_MEGA_KICK:				.dsb 1 ; 3e
SFX_HEADBUTT:				.dsb 1 ; 3f
SFX_HORN_ATTACK:			.dsb 1 ; 40
SFX_TACKLE:				.dsb 1 ; 41
SFX_POISON_STING:			.dsb 1 ; 42
SFX_POWDER:				.dsb 1 ; 43
SFX_DOUBLESLAP:				.dsb 1 ; 44
SFX_BITE:				.dsb 1 ; 45
SFX_JUMP_KICK:				.dsb 1 ; 46
SFX_STOMP:				.dsb 1 ; 47
SFX_TAIL_WHIP:				.dsb 1 ; 48
SFX_KARATE_CHOP:			.dsb 1 ; 49
SFX_SUBMISSION:				.dsb 1 ; 4a
SFX_WATER_GUN:				.dsb 1 ; 4b
SFX_SWORDS_DANCE:			.dsb 1 ; 4c
SFX_THUNDER:				.dsb 1 ; 4d
SFX_SUPERSONIC:				.dsb 1 ; 4e
SFX_LEER:				.dsb 1 ; 4f
SFX_EMBER:				.dsb 1 ; 50
SFX_BUBBLEBEAM:				.dsb 1 ; 51
SFX_HYDRO_PUMP:				.dsb 1 ; 52
SFX_SURF:				.dsb 1 ; 53
SFX_PSYBEAM:				.dsb 1 ; 54
SFX_CHARGE:				.dsb 1 ; 55
SFX_THUNDERSHOCK:			.dsb 1 ; 56
SFX_PSYCHIC:				.dsb 1 ; 57
SFX_SCREECH:				.dsb 1 ; 58
SFX_BONE_CLUB:				.dsb 1 ; 59
SFX_SHARPEN:				.dsb 1 ; 5a
SFX_EGG_BOMB:				.dsb 1 ; 5b
SFX_SING:				.dsb 1 ; 5c
SFX_HYPER_BEAM:				.dsb 1 ; 5d
SFX_SHINE:				.dsb 1 ; 5e
SFX_UNKNOWN_5F:				.dsb 1 ; 5f
SFX_UNKNOWN_60:				.dsb 1 ; 60
SFX_UNKNOWN_61:				.dsb 1 ; 61
SFX_SWITCH_POCKETS:			.dsb 1 ; 62
SFX_UNKNOWN_63:				.dsb 1 ; 63
SFX_BURN:				.dsb 1 ; 64
SFX_TITLE_SCREEN_ENTRANCE:		.dsb 1 ; 65
SFX_UNKNOWN_66:				.dsb 1 ; 66
SFX_GET_COIN_FROM_SLOTS:		.dsb 1 ; 67
SFX_PAY_DAY:				.dsb 1 ; 68
SFX_METRONOME:				.dsb 1 ; 69
SFX_CALL:				.dsb 1 ; 6a
SFX_HANG_UP:				.dsb 1 ; 6b
SFX_NO_SIGNAL:				.dsb 1 ; 6c
SFX_SANDSTORM:				.dsb 1 ; 6d
SFX_ELEVATOR:				.dsb 1 ; 6e
SFX_PROTECT:				.dsb 1 ; 6f
SFX_SKETCH:				.dsb 1 ; 70
SFX_RAIN_DANCE:				.dsb 1 ; 71
SFX_AEROBLAST:				.dsb 1 ; 72
SFX_SPARK:				.dsb 1 ; 73
SFX_CURSE:				.dsb 1 ; 74
SFX_RAGE:				.dsb 1 ; 75
SFX_THIEF:				.dsb 1 ; 76
SFX_THIEF_2:				.dsb 1 ; 77
SFX_SPIDER_WEB:				.dsb 1 ; 78
SFX_MIND_READER:			.dsb 1 ; 79
SFX_NIGHTMARE:				.dsb 1 ; 7a
SFX_SNORE:				.dsb 1 ; 7b
SFX_SWEET_KISS:				.dsb 1 ; 7c
SFX_SWEET_KISS_2:			.dsb 1 ; 7d
SFX_BELLY_DRUM:				.dsb 1 ; 7e
SFX_TOXIC:				.dsb 1 ; 7f
SFX_SLUDGE_BOMB:			.dsb 1 ; 80
SFX_FORESIGHT:				.dsb 1 ; 81
SFX_SPITE:				.dsb 1 ; 82
SFX_OUTRAGE:				.dsb 1 ; 83
SFX_PERISH_SONG:			.dsb 1 ; 84
SFX_GIGA_DRAIN:				.dsb 1 ; 85
SFX_ATTRACT:				.dsb 1 ; 86
SFX_KINESIS_2:				.dsb 1 ; 87
SFX_ZAP_CANNON:				.dsb 1 ; 88
SFX_MEAN_LOOK:				.dsb 1 ; 89
SFX_HEAL_BELL:				.dsb 1 ; 8a
SFX_RETURN:				.dsb 1 ; 8b
SFX_EXP_BAR:				.dsb 1 ; 8c
SFX_MILK_DRINK:				.dsb 1 ; 8d
SFX_PRESENT:				.dsb 1 ; 8e
SFX_MORNING_SUN:			.dsb 1 ; 8f
SFX_LEVEL_UP:				.dsb 1 ; 90
SFX_KEY_ITEM:				.dsb 1 ; 91
SFX_FANFARE_2:				.dsb 1 ; 92
SFX_REGISTER_PHONE_NUMBER:		.dsb 1 ; 93
SFX_3RD_PLACE:				.dsb 1 ; 94
SFX_GET_EGG_UNUSED:			.dsb 1 ; 95
SFX_GET_EGG:				.dsb 1 ; 96
SFX_MOVE_DELETED:			.dsb 1 ; 97
SFX_2ND_PLACE:				.dsb 1 ; 98
SFX_1ST_PLACE:				.dsb 1 ; 99
SFX_CHOOSE_A_CARD:			.dsb 1 ; 9a
SFX_GET_TM:				.dsb 1 ; 9b
SFX_GET_BADGE:				.dsb 1 ; 9c
SFX_QUIT_SLOTS:				.dsb 1 ; 9d
SFX_EGG_CRACK:				.dsb 1 ; 9e
SFX_DEX_FANFARE_LESS_THAN_20:		.dsb 1 ; 9f
SFX_DEX_FANFARE_140_169:		.dsb 1 ; a0
SFX_DEX_FANFARE_170_199:		.dsb 1 ; a1
SFX_DEX_FANFARE_200_229:		.dsb 1 ; a2
SFX_DEX_FANFARE_230_PLUS:		.dsb 1 ; a3
SFX_EVOLVED:				.dsb 1 ; a4
SFX_MASTER_BALL:			.dsb 1 ; a5
SFX_EGG_HATCH:				.dsb 1 ; a6
SFX_GS_INTRO_CHARIZARD_FIREBALL:	.dsb 1 ; a7
SFX_GS_INTRO_POKEMON_APPEARS:		.dsb 1 ; a8
SFX_FLASH:				.dsb 1 ; a9
SFX_GAME_FREAK_LOGO_GS:			.dsb 1 ; aa
SFX_NOT_VERY_EFFECTIVE:			.dsb 1 ; ab
SFX_DAMAGE:				.dsb 1 ; ac
SFX_SUPER_EFFECTIVE:			.dsb 1 ; ad
SFX_BALL_BOUNCE:			.dsb 1 ; ae
SFX_MOONLIGHT:				.dsb 1 ; af
SFX_ENCORE:				.dsb 1 ; b0
SFX_BEAT_UP:				.dsb 1 ; b1
SFX_BATON_PASS:				.dsb 1 ; b2
SFX_BALL_WOBBLE:			.dsb 1 ; b3
SFX_SWEET_SCENT:			.dsb 1 ; b4
SFX_SWEET_SCENT_2:			.dsb 1 ; b5
SFX_HIT_END_OF_EXP_BAR:			.dsb 1 ; b6
SFX_GIVE_TRADEMON:			.dsb 1 ; b7
SFX_GET_TRADEMON:			.dsb 1 ; b8
SFX_TRAIN_ARRIVED:			.dsb 1 ; b9
SFX_STOP_SLOT:				.dsb 1 ; ba
SFX_2_BOOPS:				.dsb 1 ; bb
NUM_SFX:
.ende
