NAME_LENGTH = 11
PLAYER_NAME_LENGTH = 8
BOX_NAME_LENGTH = 9
MON_NAME_LENGTH = 11
MOVE_NAME_LENGTH = 13
ITEM_NAME_LENGTH = 13
TRAINER_CLASS_NAME_LENGTH = 13
NAME_LENGTH_JAPANESE = 6

.enum 1
MON_NAME:	.dsb 1
MOVE_NAME:	.dsb 1
DUMMY_NAME:	.dsb 1
ITME_NAME:	.dsb 1
PARTY_OT_NAME:	.dsb 1
ENEMY_OT_NAME:	.dsb 1
TRAINER_NAME:	.dsb 1
MOVE_DESC_NAME_BROKEN:
.ende

BORDER_WIDTH = 2
TEXTBOX_WIDTH = SCREEN_WIDTH
TEXTBOX_INNERW = TEXTBOX_WIDTH - BORDER_WIDTH
TEXTBOX_HEIGHT = 6
TEXTBOX_INNERH = TEXTBOX_HEIGHT - BORDER_WIDTH
TEXTBOX_X = 0
TEXTBOX_INNERX = TEXTBOX_X + 1
TEXTBOX_Y = SCREEN_HEIGHT - TEXTBOX_HEIGHT
TEXTBOX_INNERY = TEXTBOX_Y + 2

TEXTBOX_FRAME_TILES = 6

.enum 5
PRINTNUM_MONEY_F:	.dsb 1
PRINTNUM_LEFTALIGN_F:	.dsb 1
PRINTNUM_LEADINGZEROS_F:
.ende

PRINTNUM_MONEY = 1 << PRINTNUM_MONEY_F
PRINTNUM_LEFTALIGN = 1 << PRINTNUM_LEFTALIGN_F
PRINTNUM_LEADINGZEROS = 1 << PRINTNUM_LEADINGZEROS_F

FIRST_REGULAR_TEXT_CHAR = 0
FIRST_UNOWN_CHAR = $40
