Cries:
	dba_audio Cry_Nidoran_M
	dba_audio Cry_Nidoran_F
	dba_audio Cry_Slowpoke
	dba_audio Cry_Kangaskhan
	dba_audio Cry_Charmander
	dba_audio Cry_Grimer
	dba_audio Cry_Voltorb
	dba_audio Cry_Muk
	dba_audio Cry_Oddish
	dba_audio Cry_Raichu
	dba_audio Cry_Nidoqueen
	dba_audio Cry_Diglett
	dba_audio Cry_Seel
	dba_audio Cry_Drowzee
	dba_audio Cry_Pidgey
	dba_audio Cry_Bulbasaur
	dba_audio Cry_Spearow
	dba_audio Cry_Rhydon
	dba_audio Cry_Golem
	dba_audio Cry_Blastoise
	dba_audio Cry_Pidgeotto
	dba_audio Cry_Weedle
	dba_audio Cry_Caterpie
	dba_audio Cry_Ekans
	dba_audio Cry_Fearow
	dba_audio Cry_Clefairy
	dba_audio Cry_Venonat
	dba_audio Cry_Lapras
	dba_audio Cry_Metapod
	dba_audio Cry_Squirtle
	dba_audio Cry_Paras
	dba_audio Cry_Growlithe
	dba_audio Cry_Krabby
	dba_audio Cry_Psyduck
	dba_audio Cry_Rattata
	dba_audio Cry_Vileplume
	dba_audio Cry_Vulpix
	dba_audio Cry_Weepinbell

	dba_audio Cry_Crow
	dba_audio Cry_Derble4
	dba_audio Cry_Derble1
	dba_audio Cry_Feline
	dba_audio Cry_Tyranitar
	dba_audio Cry_Bleet1
	dba_audio Cry_Derble2
	dba_audio Cry_Hoothoot
	dba_audio Cry_Phanpy
	dba_audio Cry_Slowking
	dba_audio Cry_Growl
	dba_audio Cry_Chikorita
	dba_audio Cry_Roar60
	dba_audio Cry_Miltank
	dba_audio Cry_Cottoncat
	dba_audio Cry_Hitmontop
	dba_audio Cry_Ledyba
	dba_audio Cry_Tiger
	dba_audio Cry_Sneasel
	dba_audio Cry_Mantine
	dba_audio Cry_Lugia
	dba_audio Cry_Madame
	dba_audio Cry_Roar30
	dba_audio Cry_Roar40
	dba_audio Cry_Roar50
	dba_audio Cry_Suicune
	dba_audio Cry_Mouse
	dba_audio Cry_HoOh
	dba_audio Cry_Granbull
	dba_audio Cry_Donphan
