Cries:
	dba PRG_Cries, Cry_Nidoran_M
	dba PRG_Cries, Cry_Nidoran_F
	dba PRG_Cries, Cry_Slowpoke
	dba PRG_Cries, Cry_Kangaskhan
	dba PRG_Cries, Cry_Charmander
	dba PRG_Cries, Cry_Grimer
	dba PRG_Cries, Cry_Voltorb
	dba PRG_Cries, Cry_Muk
	dba PRG_Cries, Cry_Oddish
	dba PRG_Cries, Cry_Raichu
	dba PRG_Cries, Cry_Nidoqueen
	dba PRG_Cries, Cry_Diglett
	dba PRG_Cries, Cry_Seel
	dba PRG_Cries, Cry_Drowzee
	dba PRG_Cries, Cry_Pidgey
	dba PRG_Cries, Cry_Bulbasaur
	dba PRG_Cries, Cry_Spearow
	dba PRG_Cries, Cry_Rhydon
	dba PRG_Cries, Cry_Golem
	dba PRG_Cries, Cry_Blastoise
	dba PRG_Cries, Cry_Pidgeotto
	dba PRG_Cries, Cry_Weedle
	dba PRG_Cries, Cry_Caterpie
	dba PRG_Cries, Cry_Ekans
	dba PRG_Cries, Cry_Fearow
	dba PRG_Cries, Cry_Clefairy
	dba PRG_Cries, Cry_Venonat
	dba PRG_Cries, Cry_Lapras
	dba PRG_Cries, Cry_Metapod
	dba PRG_Cries, Cry_Squirtle
	dba PRG_Cries, Cry_Paras
	dba PRG_Cries, Cry_Growlithe
	dba PRG_Cries, Cry_Krabby
	dba PRG_Cries, Cry_Psyduck
	dba PRG_Cries, Cry_Rattata
	dba PRG_Cries, Cry_Vileplume
	dba PRG_Cries, Cry_Vulpix
	dba PRG_Cries, Cry_Weepinbell

	dba PRG_Cries, Cry_Crow
	dba PRG_Cries, Cry_Derble4
	dba PRG_Cries, Cry_Derble1
	dba PRG_Cries, Cry_Feline
	dba PRG_Cries, Cry_Tyranitar
	dba PRG_Cries, Cry_Bleet1
	dba PRG_Cries, Cry_Derble2
	dba PRG_Cries, Cry_Hoothoot
	dba PRG_Cries, Cry_Phanpy
	dba PRG_Cries, Cry_Slowking
	dba PRG_Cries, Cry_Growl
	dba PRG_Cries, Cry_Chikorita
	dba PRG_Cries, Cry_Roar60
	dba PRG_Cries, Cry_Miltank
	dba PRG_Cries, Cry_Cottoncat
	dba PRG_Cries, Cry_Hitmontop
	dba PRG_Cries, Cry_Ledyba
	dba PRG_Cries, Cry_Tiger
	dba PRG_Cries, Cry_Sneasel
	dba PRG_Cries, Cry_Mantine
	dba PRG_Cries, Cry_Lugia
	dba PRG_Cries, Cry_Madame
	dba PRG_Cries, Cry_Roar30
	dba PRG_Cries, Cry_Roar40
	dba PRG_Cries, Cry_Roar50
	dba PRG_Cries, Cry_Suicune
	dba PRG_Cries, Cry_Mouse
	dba PRG_Cries, Cry_HoOh
	dba PRG_Cries, Cry_Granbull
	dba PRG_Cries, Cry_Donphan
