Music:
	dba PRG_Audio,  Music_Nothing
	dba PRG_Music3, Music_TitleScreen
	dba PRG_Music0, Music_Route1
	dba PRG_Music0, Music_Route3
	dba PRG_Music0, Music_Route11
	dba PRG_Music4, Music_MagnetTrain
	dba PRG_Music0, Music_KantoGymBattle
	dba PRG_Music0, Music_KantoTrainerBattle
	dba PRG_Music0, Music_KantoWildBattle
	dba PRG_Music0, Music_PokemonCenter
	dba PRG_Music2, Music_LookHiker
	dba PRG_Music0, Music_LookLass
	dba PRG_Music0, Music_LookOfficer
	dba PRG_Music1, Music_HealPokemon
	dba PRG_Music4, Music_LavenderTown
	dba PRG_Music0, Music_Route2
	dba PRG_Music0, Music_MtMoon
	dba PRG_Music0, Music_ShowMeAround
	dba PRG_Music4, Music_GameCorner
	dba PRG_Music4, Music_Bicycle
	dba PRG_Music1, Music_HallOfFame
	dba PRG_Music2, Music_ViridianCity
	dba PRG_Music2, Music_CeladonCity
	dba PRG_Music3, Music_TrainerVictory
	dba PRG_Music2, Music_WildPokemonVictory
	dba PRG_Music2, Music_GymLeaderVictory
	dba PRG_Music2, Music_MtMoonSquare
	dba PRG_Music2, Music_Gym
	dba PRG_Music2, Music_PalletTown
	dba PRG_Music2, Music_ProfOaksPokemonTalk
	dba PRG_Music1, Music_Evolution
	dba PRG_Music3, Music_Credits
	dba PRG_Music2, Music_CherrygroveCity
	dba PRG_Music2, Music_UnionCave
	dba PRG_Music4, Music_EcruteakCity
	dba PRG_Music1, Music_VioletCity
	dba PRG_Music3, Music_RivalBattle
	dba PRG_Music3, Music_RocketBattle
	dba PRG_Music1, Music_Route29
	dba PRG_Music3, Music_Route34
	dba PRG_Music2, Music_LookYoungster
	dba PRG_Music3, Music_GoldenrodCity
	dba PRG_Music2, Music_TinTower
	dba PRG_Music2, Music_SuccessfulCapture
	dba PRG_Music2, Music_PokemonMarch
	dba PRG_Music1, Music_Printer
	dba PRG_Music4, Music_TheEnd
