Music:
	dba_audio Music_Nothing
	dba_audio Music_TitleScreen
	dba_audio Music_Route1
	dba_audio Music_Route3
	dba_audio Music_Route11
	dba_audio Music_MagnetTrain
	dba_audio Music_KantoGymBattle
	dba_audio Music_KantoTrainerBattle
	dba_audio Music_KantoWildBattle
	dba_audio Music_PokemonCenter
	dba_audio Music_LookHiker
	dba_audio Music_LookLass
	dba_audio Music_LookOfficer
	dba_audio Music_HealPokemon
	dba_audio Music_LavenderTown
	dba_audio Music_Route2
	dba_audio Music_MtMoon
	dba_audio Music_ShowMeAround
	dba_audio Music_GameCorner
	dba_audio Music_Bicycle
	dba_audio Music_HallOfFame
	dba_audio Music_ViridianCity
	dba_audio Music_CeladonCity
	dba_audio Music_TrainerVictory
	dba_audio Music_WildPokemonVictory
	dba_audio Music_GymLeaderVictory
	dba_audio Music_MtMoonSquare
	dba_audio Music_Gym
	dba_audio Music_PalletTown
	dba_audio Music_ProfOaksPokemonTalk
	dba_audio Music_ProfOak
	dba_audio Music_LookRival
	dba_audio Music_AfterTheRivalFight
	dba_audio Music_Surf
	dba_audio Music_Evolution
	dba_audio Music_NationalPark
	dba_audio Music_Credits
	dba_audio Music_AzaleaTown
	dba_audio Music_CherrygroveCity
	dba_audio Music_UnionCave
	dba_audio Music_JohtoWildBattle
	dba_audio Music_EcruteakCity
	dba_audio Music_VioletCity
	dba_audio Music_RivalBattle
	dba_audio Music_RocketBattle
	dba_audio Music_Route29
	dba_audio Music_Route34
	dba_audio Music_LookYoungster
	dba_audio Music_GoldenrodCity
	dba_audio Music_TinTower
	dba_audio Music_JohtoWildBattleNight
	dba_audio Music_SuccessfulCapture
	dba_audio Music_PokemonMarch
	dba_audio Music_Printer
	dba_audio Music_TheEnd
