SFX:
	dba_audio SFX_LevelUp
	dba_audio SFX_Item
	dba_audio SFX_Evolution
	dba_audio Sfx_PokeballsPlacedOnTable
	dba_audio Sfx_Potion
	dba_audio Sfx_FullHeal
	dba_audio Sfx_Menu
	dba_audio Sfx_ReadText
	dba_audio Sfx_ReadText
	dba_audio Sfx_DexFanfare2049
	dba_audio Sfx_DexFanfare80109
	dba_audio Sfx_Poison
	dba_audio Sfx_GotSafariBalls
	dba_audio Sfx_BootPc
	dba_audio Sfx_ShutDownPC
	dba_audio Sfx_ChoosePCOption
	dba_audio Sfx_EscapeRope
	dba_audio Sfx_PushButton
	dba_audio Sfx_SecondPartOfItemfinder
	dba_audio Sfx_WarpTo
	dba_audio Sfx_WarpFrom
	dba_audio Sfx_ChangeDexMode
	dba_audio Sfx_JumpOverLedge
	dba_audio Sfx_GrassRustle
	dba_audio Sfx_Fly
	dba_audio Sfx_Wrong
	dba_audio Sfx_Squeak
	dba_audio Sfx_Strength
	dba_audio Sfx_Boat
	dba_audio Sfx_WallOpen
	dba_audio Sfx_PlacePuzzlePieceDown
	dba_audio Sfx_EnterDoor
	dba_audio Sfx_SwitchPokemon
	dba_audio Sfx_Tally
	dba_audio Sfx_Transaction
	dba_audio Sfx_ExitBuilding
	dba_audio Sfx_Bump
	dba_audio Sfx_Save
	dba_audio Sfx_Pokeflute
	dba_audio Sfx_ElevatorEnd
	dba_audio Sfx_ThrowBall
	dba_audio Sfx_BallPoof
	dba_audio Sfx_Unknown3A
	dba_audio Sfx_Run
	dba_audio Sfx_SlotMachineStart
	dba_audio Sfx_Fanfare
	dba_audio Sfx_Peck
	dba_audio Sfx_Kinesis
	dba_audio Sfx_Lick
	dba_audio Sfx_Pound
	dba_audio Sfx_MovePuzzlePiece
	dba_audio Sfx_CometPunch
	dba_audio Sfx_MegaPunch
	dba_audio Sfx_Elevator
