SFX:
	dba_audio Sfx_LevelUp
	dba_audio SFX_Item
	dba_audio SFX_Evolution
	dba_audio Sfx_PokeballsPlacedOnTable
	dba_audio Sfx_Potion
	dba_audio Sfx_FullHeal
	dba_audio Sfx_Menu
	dba_audio Sfx_ReadText
	dba_audio Sfx_ReadText
	dba_audio Sfx_DexFanfare2049
	dba_audio Sfx_DexFanfare80109
	dba_audio Sfx_Poison
	dba_audio Sfx_GotSafariBalls
	dba_audio Sfx_BootPc
	dba_audio Sfx_ShutDownPC
	dba_audio Sfx_ChoosePCOption
	dba_audio Sfx_EscapeRope
	dba_audio Sfx_PushButton
	dba_audio Sfx_SecondPartOfItemfinder
	dba_audio Sfx_WarpTo
	dba_audio Sfx_WarpFrom
	dba_audio Sfx_ChangeDexMode
	dba_audio Sfx_JumpOverLedge
	dba_audio Sfx_GrassRustle
	dba_audio Sfx_Fly
	dba_audio Sfx_Wrong
	dba_audio Sfx_Squeak
	dba_audio Sfx_Strength
	dba_audio Sfx_Boat
	dba_audio Sfx_WallOpen
	dba_audio Sfx_PlacePuzzlePieceDown
	dba_audio Sfx_EnterDoor
	dba_audio Sfx_SwitchPokemon
	dba_audio Sfx_Tally
	dba_audio Sfx_Transaction
	dba_audio Sfx_ExitBuilding
	dba_audio Sfx_Bump
	dba_audio Sfx_Save
	dba_audio Sfx_Pokeflute
	dba_audio Sfx_ElevatorEnd
	dba_audio Sfx_ThrowBall
	dba_audio Sfx_BallPoof
	dba_audio Sfx_Unknown3A
	dba_audio Sfx_Run
	dba_audio Sfx_SlotMachineStart
	dba_audio Sfx_Fanfare
	dba_audio Sfx_Peck
	dba_audio Sfx_Kinesis
	dba_audio Sfx_Lick
	dba_audio Sfx_Pound
	dba_audio Sfx_MovePuzzlePiece
	dba_audio Sfx_CometPunch
	dba_audio Sfx_MegaPunch
	dba_audio Sfx_Scratch
	dba_audio Sfx_Vicegrip
	dba_audio Sfx_RazorWind
	dba_audio Sfx_Cut
	dba_audio Sfx_WingAttack
	dba_audio Sfx_Whirlwind
	dba_audio Sfx_Bind
	dba_audio Sfx_VineWhip
	dba_audio Sfx_DoubleKick
	dba_audio Sfx_MegaKick
	dba_audio Sfx_Headbutt
	dba_audio Sfx_HornAttack
	dba_audio Sfx_Tackle
	dba_audio Sfx_PoisonSting
	dba_audio Sfx_Powder
	dba_audio Sfx_Doubleslap
	dba_audio Sfx_Bite
	dba_audio Sfx_JumpKick
	dba_audio Sfx_Stomp
	dba_audio Sfx_TailWhip
	dba_audio Sfx_KarateChop
	dba_audio Sfx_Submission
	dba_audio Sfx_WaterGun
	dba_audio Sfx_SwordsDance
	dba_audio Sfx_Thunder
	dba_audio Sfx_Supersonic
	dba_audio Sfx_Leer
	dba_audio Sfx_Ember
	dba_audio Sfx_Bubblebeam
	dba_audio Sfx_HydroPump
	dba_audio Sfx_Surf
	dba_audio Sfx_Psybeam
	dba_audio Sfx_Charge
	dba_audio Sfx_Thundershock
	dba_audio Sfx_Psychic
	dba_audio Sfx_Screech
	dba_audio Sfx_BoneClub
	dba_audio Sfx_Sharpen
	;dba_audio Sfx_EggBomb
	;dba_audio Sfx_Sing
	;dba_audio Sfx_HyperBeam
	;dba_audio Sfx_Shine
	;dba_audio Sfx_Unknown5F
	;dba_audio Sfx_Unknown60
	;dba_audio Sfx_Unknown61
	;dba_audio Sfx_SwitchPockets
	;dba_audio Sfx_Unknown63
	;dba_audio Sfx_Burn
	;dba_audio Sfx_TitleScreenEntrance
	;dba_audio Sfx_Unknown66
	;dba_audio Sfx_GetCoinFromSlots
	;dba_audio Sfx_PayDay
	;dba_audio Sfx_Metronome
	;dba_audio Sfx_Call
	;dba_audio Sfx_HangUp
	;dba_audio Sfx_NoSignal
	;dba_audio Sfx_Sandstorm
	dba_audio Sfx_Elevator
	dba_audio Sfx_Protect
	dba_audio Sfx_Sketch
	dba_audio Sfx_RainDance
	;dba_audio Sfx_Aeroblast
	;dba_audio Sfx_Spark
	;dba_audio Sfx_Curse
	;dba_audio Sfx_Rage
	;dba_audio Sfx_Thief
	;dba_audio Sfx_Thief2
	;dba_audio Sfx_SpiderWeb
	;dba_audio Sfx_MindReader
	;dba_audio Sfx_Nightmare
	;dba_audio Sfx_Snore
	;dba_audio Sfx_SweetKiss
	;dba_audio Sfx_SweetKiss2
	;dba_audio Sfx_BellyDrum
	;dba_audio Sfx_Unknown7F
	;dba_audio Sfx_SludgeBomb
	;dba_audio Sfx_Foresight
	;dba_audio Sfx_Spite
	;dba_audio Sfx_Outrage
	;dba_audio Sfx_PerishSong
	;dba_audio Sfx_GigaDrain
	;dba_audio Sfx_Attract
	;dba_audio Sfx_Kinesis2
	;dba_audio Sfx_ZapCannon
	;dba_audio Sfx_MeanLook
	;dba_audio Sfx_HealBell
	;dba_audio Sfx_Return
	;dba_audio Sfx_ExpBar
	;dba_audio Sfx_MilkDrink
	;dba_audio Sfx_Present
	;dba_audio Sfx_MorningSun
	dba_audio Sfx_LevelUp
	dba_audio Sfx_KeyItem
	dba_audio Sfx_Fanfare2
	dba_audio Sfx_RegisterPhoneNumber
	dba_audio Sfx_3rdPlace
	dba_audio Sfx_UnincludedFanfare
	dba_audio Sfx_GetEgg
	dba_audio Sfx_MoveDeleted
	dba_audio Sfx_2ndPlace
	dba_audio Sfx_1stPlace
	dba_audio Sfx_ChooseACard
	dba_audio Sfx_GetTm
	dba_audio Sfx_GetBadge
	dba_audio Sfx_QuitSlots
	dba_audio Sfx_EggCrack
	dba_audio Sfx_DexFanfareLessThan20
	dba_audio Sfx_DexFanfare140169
	dba_audio Sfx_DexFanfare170199
	dba_audio Sfx_DexFanfare200229
	dba_audio Sfx_DexFanfare230Plus
	dba_audio Sfx_Evolved
	dba_audio Sfx_MasterBall
	dba_audio Sfx_EggHatch
	dba_audio Sfx_GsIntroCharizardFireball
	dba_audio Sfx_GsIntroPokemonAppears
	dba_audio Sfx_Flash
	dba_audio Sfx_GameFreakLogoGs
	dba_audio Sfx_NotVeryEffective
	dba_audio Sfx_Damage
	dba_audio Sfx_SuperEffective
	dba_audio Sfx_BallBounce
	;dba_audio Sfx_Moonlight
	;dba_audio Sfx_Encore
	;dba_audio Sfx_BeatUp
	;dba_audio Sfx_BatonPass
	;dba_audio Sfx_BallWobble
	;dba_audio Sfx_SweetScent
	;dba_audio Sfx_SweetScent2
	;dba_audio Sfx_HitEndOfExpBar
	;dba_audio Sfx_GiveTrademon
	;dba_audio Sfx_GetTrademon
	;dba_audio Sfx_TrainArrived
	;dba_audio Sfx_StopSlot
	;dba_audio Sfx_2Boops
