.include "src/audio/engine.asm"
.include "src/audio/music-pointers.asm"
.include "src/audio/music/nothing.asm"
.include "src/audio/cry-pointers.asm"
.include "src/audio/sfx-pointers.asm"

.include "src/audio/music/healpokemon.asm"
.include "src/audio/music/lookyoungster.asm"
.include "src/audio/music/bicycle.asm"
.include "src/audio/music/unioncave.asm"
.include "src/audio/music/goldenrodcity.asm"
.include "src/audio/music/gamecorner.asm"
