.include "src/def/audio-constants.asm"
.include "src/def/cry-constants.asm"
.include "src/def/pokemon-data-constants.asm"
.include "src/def/hardware.asm"
.include "src/def/prg.asm"
.include "src/def/misc.asm"
.include "src/def/battle.asm"
.include "src/def/text.asm"
